// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_battle.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_game_5fbattle_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_game_5fbattle_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
#include "game_types.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_game_5fbattle_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_game_5fbattle_2eproto {
  static const uint32_t offsets[];
};
namespace PB {
namespace BattleInternal {
class BattleCreateReq;
struct BattleCreateReqDefaultTypeInternal;
extern BattleCreateReqDefaultTypeInternal _BattleCreateReq_default_instance_;
class BattleCreateResp;
struct BattleCreateRespDefaultTypeInternal;
extern BattleCreateRespDefaultTypeInternal _BattleCreateResp_default_instance_;
}  // namespace BattleInternal
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> ::PB::BattleInternal::BattleCreateReq* Arena::CreateMaybeMessage<::PB::BattleInternal::BattleCreateReq>(Arena*);
template<> ::PB::BattleInternal::BattleCreateResp* Arena::CreateMaybeMessage<::PB::BattleInternal::BattleCreateResp>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace PB {
namespace BattleInternal {

enum BattleCreateReq_MsgId : int {
  BattleCreateReq_MsgId_None = 0,
  BattleCreateReq_MsgId_Id = 60000,
  BattleCreateReq_MsgId_BattleCreateReq_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  BattleCreateReq_MsgId_BattleCreateReq_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool BattleCreateReq_MsgId_IsValid(int value);
constexpr BattleCreateReq_MsgId BattleCreateReq_MsgId_MsgId_MIN = BattleCreateReq_MsgId_None;
constexpr BattleCreateReq_MsgId BattleCreateReq_MsgId_MsgId_MAX = BattleCreateReq_MsgId_Id;
constexpr int BattleCreateReq_MsgId_MsgId_ARRAYSIZE = BattleCreateReq_MsgId_MsgId_MAX + 1;

const std::string& BattleCreateReq_MsgId_Name(BattleCreateReq_MsgId value);
template<typename T>
inline const std::string& BattleCreateReq_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BattleCreateReq_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BattleCreateReq_MsgId_Name.");
  return BattleCreateReq_MsgId_Name(static_cast<BattleCreateReq_MsgId>(enum_t_value));
}
bool BattleCreateReq_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleCreateReq_MsgId* value);
enum BattleCreateResp_MsgId : int {
  BattleCreateResp_MsgId_None = 0,
  BattleCreateResp_MsgId_Id = 60001,
  BattleCreateResp_MsgId_BattleCreateResp_MsgId_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  BattleCreateResp_MsgId_BattleCreateResp_MsgId_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool BattleCreateResp_MsgId_IsValid(int value);
constexpr BattleCreateResp_MsgId BattleCreateResp_MsgId_MsgId_MIN = BattleCreateResp_MsgId_None;
constexpr BattleCreateResp_MsgId BattleCreateResp_MsgId_MsgId_MAX = BattleCreateResp_MsgId_Id;
constexpr int BattleCreateResp_MsgId_MsgId_ARRAYSIZE = BattleCreateResp_MsgId_MsgId_MAX + 1;

const std::string& BattleCreateResp_MsgId_Name(BattleCreateResp_MsgId value);
template<typename T>
inline const std::string& BattleCreateResp_MsgId_Name(T enum_t_value) {
  static_assert(::std::is_same<T, BattleCreateResp_MsgId>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function BattleCreateResp_MsgId_Name.");
  return BattleCreateResp_MsgId_Name(static_cast<BattleCreateResp_MsgId>(enum_t_value));
}
bool BattleCreateResp_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleCreateResp_MsgId* value);
// ===================================================================

class BattleCreateReq final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.BattleInternal.BattleCreateReq) */ {
 public:
  inline BattleCreateReq() : BattleCreateReq(nullptr) {}
  ~BattleCreateReq() override;
  explicit PROTOBUF_CONSTEXPR BattleCreateReq(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattleCreateReq(const BattleCreateReq& from);
  BattleCreateReq(BattleCreateReq&& from) noexcept
    : BattleCreateReq() {
    *this = ::std::move(from);
  }

  inline BattleCreateReq& operator=(const BattleCreateReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattleCreateReq& operator=(BattleCreateReq&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BattleCreateReq& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattleCreateReq* internal_default_instance() {
    return reinterpret_cast<const BattleCreateReq*>(
               &_BattleCreateReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BattleCreateReq& a, BattleCreateReq& b) {
    a.Swap(&b);
  }
  inline void Swap(BattleCreateReq* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattleCreateReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattleCreateReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattleCreateReq>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BattleCreateReq& from);
  void MergeFrom(const BattleCreateReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleCreateReq* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.BattleInternal.BattleCreateReq";
  }
  protected:
  explicit BattleCreateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef BattleCreateReq_MsgId MsgId;
  static constexpr MsgId None =
    BattleCreateReq_MsgId_None;
  static constexpr MsgId Id =
    BattleCreateReq_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return BattleCreateReq_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    BattleCreateReq_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    BattleCreateReq_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    BattleCreateReq_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return BattleCreateReq_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return BattleCreateReq_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPlayersFieldNumber = 3,
    kBattleIdFieldNumber = 1,
    kMapIdFieldNumber = 2,
    kRequesterServiceIdFieldNumber = 4,
    kRequesterInstanceIdFieldNumber = 5,
  };
  // repeated .PB.Types.BattlePlayerSpec players = 3;
  int players_size() const;
  private:
  int _internal_players_size() const;
  public:
  void clear_players();
  ::PB::Types::BattlePlayerSpec* mutable_players(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::BattlePlayerSpec >*
      mutable_players();
  private:
  const ::PB::Types::BattlePlayerSpec& _internal_players(int index) const;
  ::PB::Types::BattlePlayerSpec* _internal_add_players();
  public:
  const ::PB::Types::BattlePlayerSpec& players(int index) const;
  ::PB::Types::BattlePlayerSpec* add_players();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::BattlePlayerSpec >&
      players() const;

  // uint32 battle_id = 1;
  void clear_battle_id();
  uint32_t battle_id() const;
  void set_battle_id(uint32_t value);
  private:
  uint32_t _internal_battle_id() const;
  void _internal_set_battle_id(uint32_t value);
  public:

  // int32 map_id = 2;
  void clear_map_id();
  int32_t map_id() const;
  void set_map_id(int32_t value);
  private:
  int32_t _internal_map_id() const;
  void _internal_set_map_id(int32_t value);
  public:

  // uint32 requester_service_id = 4;
  void clear_requester_service_id();
  uint32_t requester_service_id() const;
  void set_requester_service_id(uint32_t value);
  private:
  uint32_t _internal_requester_service_id() const;
  void _internal_set_requester_service_id(uint32_t value);
  public:

  // uint32 requester_instance_id = 5;
  void clear_requester_instance_id();
  uint32_t requester_instance_id() const;
  void set_requester_instance_id(uint32_t value);
  private:
  uint32_t _internal_requester_instance_id() const;
  void _internal_set_requester_instance_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.BattleInternal.BattleCreateReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::BattlePlayerSpec > players_;
    uint32_t battle_id_;
    int32_t map_id_;
    uint32_t requester_service_id_;
    uint32_t requester_instance_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fbattle_2eproto;
};
// -------------------------------------------------------------------

class BattleCreateResp final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:PB.BattleInternal.BattleCreateResp) */ {
 public:
  inline BattleCreateResp() : BattleCreateResp(nullptr) {}
  ~BattleCreateResp() override;
  explicit PROTOBUF_CONSTEXPR BattleCreateResp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BattleCreateResp(const BattleCreateResp& from);
  BattleCreateResp(BattleCreateResp&& from) noexcept
    : BattleCreateResp() {
    *this = ::std::move(from);
  }

  inline BattleCreateResp& operator=(const BattleCreateResp& from) {
    CopyFrom(from);
    return *this;
  }
  inline BattleCreateResp& operator=(BattleCreateResp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const BattleCreateResp& default_instance() {
    return *internal_default_instance();
  }
  static inline const BattleCreateResp* internal_default_instance() {
    return reinterpret_cast<const BattleCreateResp*>(
               &_BattleCreateResp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(BattleCreateResp& a, BattleCreateResp& b) {
    a.Swap(&b);
  }
  inline void Swap(BattleCreateResp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BattleCreateResp* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BattleCreateResp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BattleCreateResp>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const BattleCreateResp& from);
  void MergeFrom(const BattleCreateResp& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(BattleCreateResp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PB.BattleInternal.BattleCreateResp";
  }
  protected:
  explicit BattleCreateResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  typedef BattleCreateResp_MsgId MsgId;
  static constexpr MsgId None =
    BattleCreateResp_MsgId_None;
  static constexpr MsgId Id =
    BattleCreateResp_MsgId_Id;
  static inline bool MsgId_IsValid(int value) {
    return BattleCreateResp_MsgId_IsValid(value);
  }
  static constexpr MsgId MsgId_MIN =
    BattleCreateResp_MsgId_MsgId_MIN;
  static constexpr MsgId MsgId_MAX =
    BattleCreateResp_MsgId_MsgId_MAX;
  static constexpr int MsgId_ARRAYSIZE =
    BattleCreateResp_MsgId_MsgId_ARRAYSIZE;
  template<typename T>
  static inline const std::string& MsgId_Name(T enum_t_value) {
    static_assert(::std::is_same<T, MsgId>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function MsgId_Name.");
    return BattleCreateResp_MsgId_Name(enum_t_value);
  }
  static inline bool MsgId_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      MsgId* value) {
    return BattleCreateResp_MsgId_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 2,
    kWorldDumpFieldNumber = 6,
    kCodeFieldNumber = 1,
    kBattleIdFieldNumber = 3,
    kBattleInstanceIdFieldNumber = 4,
    kServerFrameFieldNumber = 5,
    kActorEntityIdFieldNumber = 7,
  };
  // string message = 2;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // bytes world_dump = 6;
  void clear_world_dump();
  const std::string& world_dump() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_world_dump(ArgT0&& arg0, ArgT... args);
  std::string* mutable_world_dump();
  PROTOBUF_NODISCARD std::string* release_world_dump();
  void set_allocated_world_dump(std::string* world_dump);
  private:
  const std::string& _internal_world_dump() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_world_dump(const std::string& value);
  std::string* _internal_mutable_world_dump();
  public:

  // int32 code = 1;
  void clear_code();
  int32_t code() const;
  void set_code(int32_t value);
  private:
  int32_t _internal_code() const;
  void _internal_set_code(int32_t value);
  public:

  // uint32 battle_id = 3;
  void clear_battle_id();
  uint32_t battle_id() const;
  void set_battle_id(uint32_t value);
  private:
  uint32_t _internal_battle_id() const;
  void _internal_set_battle_id(uint32_t value);
  public:

  // uint32 battle_instance_id = 4;
  void clear_battle_instance_id();
  uint32_t battle_instance_id() const;
  void set_battle_instance_id(uint32_t value);
  private:
  uint32_t _internal_battle_instance_id() const;
  void _internal_set_battle_instance_id(uint32_t value);
  public:

  // uint32 server_frame = 5;
  void clear_server_frame();
  uint32_t server_frame() const;
  void set_server_frame(uint32_t value);
  private:
  uint32_t _internal_server_frame() const;
  void _internal_set_server_frame(uint32_t value);
  public:

  // uint32 actor_entity_id = 7;
  void clear_actor_entity_id();
  uint32_t actor_entity_id() const;
  void set_actor_entity_id(uint32_t value);
  private:
  uint32_t _internal_actor_entity_id() const;
  void _internal_set_actor_entity_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PB.BattleInternal.BattleCreateResp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr world_dump_;
    int32_t code_;
    uint32_t battle_id_;
    uint32_t battle_instance_id_;
    uint32_t server_frame_;
    uint32_t actor_entity_id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_5fbattle_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BattleCreateReq

// uint32 battle_id = 1;
inline void BattleCreateReq::clear_battle_id() {
  _impl_.battle_id_ = 0u;
}
inline uint32_t BattleCreateReq::_internal_battle_id() const {
  return _impl_.battle_id_;
}
inline uint32_t BattleCreateReq::battle_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateReq.battle_id)
  return _internal_battle_id();
}
inline void BattleCreateReq::_internal_set_battle_id(uint32_t value) {
  
  _impl_.battle_id_ = value;
}
inline void BattleCreateReq::set_battle_id(uint32_t value) {
  _internal_set_battle_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateReq.battle_id)
}

// int32 map_id = 2;
inline void BattleCreateReq::clear_map_id() {
  _impl_.map_id_ = 0;
}
inline int32_t BattleCreateReq::_internal_map_id() const {
  return _impl_.map_id_;
}
inline int32_t BattleCreateReq::map_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateReq.map_id)
  return _internal_map_id();
}
inline void BattleCreateReq::_internal_set_map_id(int32_t value) {
  
  _impl_.map_id_ = value;
}
inline void BattleCreateReq::set_map_id(int32_t value) {
  _internal_set_map_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateReq.map_id)
}

// repeated .PB.Types.BattlePlayerSpec players = 3;
inline int BattleCreateReq::_internal_players_size() const {
  return _impl_.players_.size();
}
inline int BattleCreateReq::players_size() const {
  return _internal_players_size();
}
inline ::PB::Types::BattlePlayerSpec* BattleCreateReq::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:PB.BattleInternal.BattleCreateReq.players)
  return _impl_.players_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::BattlePlayerSpec >*
BattleCreateReq::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:PB.BattleInternal.BattleCreateReq.players)
  return &_impl_.players_;
}
inline const ::PB::Types::BattlePlayerSpec& BattleCreateReq::_internal_players(int index) const {
  return _impl_.players_.Get(index);
}
inline const ::PB::Types::BattlePlayerSpec& BattleCreateReq::players(int index) const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateReq.players)
  return _internal_players(index);
}
inline ::PB::Types::BattlePlayerSpec* BattleCreateReq::_internal_add_players() {
  return _impl_.players_.Add();
}
inline ::PB::Types::BattlePlayerSpec* BattleCreateReq::add_players() {
  ::PB::Types::BattlePlayerSpec* _add = _internal_add_players();
  // @@protoc_insertion_point(field_add:PB.BattleInternal.BattleCreateReq.players)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::PB::Types::BattlePlayerSpec >&
BattleCreateReq::players() const {
  // @@protoc_insertion_point(field_list:PB.BattleInternal.BattleCreateReq.players)
  return _impl_.players_;
}

// uint32 requester_service_id = 4;
inline void BattleCreateReq::clear_requester_service_id() {
  _impl_.requester_service_id_ = 0u;
}
inline uint32_t BattleCreateReq::_internal_requester_service_id() const {
  return _impl_.requester_service_id_;
}
inline uint32_t BattleCreateReq::requester_service_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateReq.requester_service_id)
  return _internal_requester_service_id();
}
inline void BattleCreateReq::_internal_set_requester_service_id(uint32_t value) {
  
  _impl_.requester_service_id_ = value;
}
inline void BattleCreateReq::set_requester_service_id(uint32_t value) {
  _internal_set_requester_service_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateReq.requester_service_id)
}

// uint32 requester_instance_id = 5;
inline void BattleCreateReq::clear_requester_instance_id() {
  _impl_.requester_instance_id_ = 0u;
}
inline uint32_t BattleCreateReq::_internal_requester_instance_id() const {
  return _impl_.requester_instance_id_;
}
inline uint32_t BattleCreateReq::requester_instance_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateReq.requester_instance_id)
  return _internal_requester_instance_id();
}
inline void BattleCreateReq::_internal_set_requester_instance_id(uint32_t value) {
  
  _impl_.requester_instance_id_ = value;
}
inline void BattleCreateReq::set_requester_instance_id(uint32_t value) {
  _internal_set_requester_instance_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateReq.requester_instance_id)
}

// -------------------------------------------------------------------

// BattleCreateResp

// int32 code = 1;
inline void BattleCreateResp::clear_code() {
  _impl_.code_ = 0;
}
inline int32_t BattleCreateResp::_internal_code() const {
  return _impl_.code_;
}
inline int32_t BattleCreateResp::code() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.code)
  return _internal_code();
}
inline void BattleCreateResp::_internal_set_code(int32_t value) {
  
  _impl_.code_ = value;
}
inline void BattleCreateResp::set_code(int32_t value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.code)
}

// string message = 2;
inline void BattleCreateResp::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& BattleCreateResp::message() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BattleCreateResp::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.message)
}
inline std::string* BattleCreateResp::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:PB.BattleInternal.BattleCreateResp.message)
  return _s;
}
inline const std::string& BattleCreateResp::_internal_message() const {
  return _impl_.message_.Get();
}
inline void BattleCreateResp::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* BattleCreateResp::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* BattleCreateResp::release_message() {
  // @@protoc_insertion_point(field_release:PB.BattleInternal.BattleCreateResp.message)
  return _impl_.message_.Release();
}
inline void BattleCreateResp::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.BattleInternal.BattleCreateResp.message)
}

// uint32 battle_id = 3;
inline void BattleCreateResp::clear_battle_id() {
  _impl_.battle_id_ = 0u;
}
inline uint32_t BattleCreateResp::_internal_battle_id() const {
  return _impl_.battle_id_;
}
inline uint32_t BattleCreateResp::battle_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.battle_id)
  return _internal_battle_id();
}
inline void BattleCreateResp::_internal_set_battle_id(uint32_t value) {
  
  _impl_.battle_id_ = value;
}
inline void BattleCreateResp::set_battle_id(uint32_t value) {
  _internal_set_battle_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.battle_id)
}

// uint32 battle_instance_id = 4;
inline void BattleCreateResp::clear_battle_instance_id() {
  _impl_.battle_instance_id_ = 0u;
}
inline uint32_t BattleCreateResp::_internal_battle_instance_id() const {
  return _impl_.battle_instance_id_;
}
inline uint32_t BattleCreateResp::battle_instance_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.battle_instance_id)
  return _internal_battle_instance_id();
}
inline void BattleCreateResp::_internal_set_battle_instance_id(uint32_t value) {
  
  _impl_.battle_instance_id_ = value;
}
inline void BattleCreateResp::set_battle_instance_id(uint32_t value) {
  _internal_set_battle_instance_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.battle_instance_id)
}

// uint32 server_frame = 5;
inline void BattleCreateResp::clear_server_frame() {
  _impl_.server_frame_ = 0u;
}
inline uint32_t BattleCreateResp::_internal_server_frame() const {
  return _impl_.server_frame_;
}
inline uint32_t BattleCreateResp::server_frame() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.server_frame)
  return _internal_server_frame();
}
inline void BattleCreateResp::_internal_set_server_frame(uint32_t value) {
  
  _impl_.server_frame_ = value;
}
inline void BattleCreateResp::set_server_frame(uint32_t value) {
  _internal_set_server_frame(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.server_frame)
}

// bytes world_dump = 6;
inline void BattleCreateResp::clear_world_dump() {
  _impl_.world_dump_.ClearToEmpty();
}
inline const std::string& BattleCreateResp::world_dump() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.world_dump)
  return _internal_world_dump();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void BattleCreateResp::set_world_dump(ArgT0&& arg0, ArgT... args) {
 
 _impl_.world_dump_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.world_dump)
}
inline std::string* BattleCreateResp::mutable_world_dump() {
  std::string* _s = _internal_mutable_world_dump();
  // @@protoc_insertion_point(field_mutable:PB.BattleInternal.BattleCreateResp.world_dump)
  return _s;
}
inline const std::string& BattleCreateResp::_internal_world_dump() const {
  return _impl_.world_dump_.Get();
}
inline void BattleCreateResp::_internal_set_world_dump(const std::string& value) {
  
  _impl_.world_dump_.Set(value, GetArenaForAllocation());
}
inline std::string* BattleCreateResp::_internal_mutable_world_dump() {
  
  return _impl_.world_dump_.Mutable(GetArenaForAllocation());
}
inline std::string* BattleCreateResp::release_world_dump() {
  // @@protoc_insertion_point(field_release:PB.BattleInternal.BattleCreateResp.world_dump)
  return _impl_.world_dump_.Release();
}
inline void BattleCreateResp::set_allocated_world_dump(std::string* world_dump) {
  if (world_dump != nullptr) {
    
  } else {
    
  }
  _impl_.world_dump_.SetAllocated(world_dump, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.world_dump_.IsDefault()) {
    _impl_.world_dump_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PB.BattleInternal.BattleCreateResp.world_dump)
}

// uint32 actor_entity_id = 7;
inline void BattleCreateResp::clear_actor_entity_id() {
  _impl_.actor_entity_id_ = 0u;
}
inline uint32_t BattleCreateResp::_internal_actor_entity_id() const {
  return _impl_.actor_entity_id_;
}
inline uint32_t BattleCreateResp::actor_entity_id() const {
  // @@protoc_insertion_point(field_get:PB.BattleInternal.BattleCreateResp.actor_entity_id)
  return _internal_actor_entity_id();
}
inline void BattleCreateResp::_internal_set_actor_entity_id(uint32_t value) {
  
  _impl_.actor_entity_id_ = value;
}
inline void BattleCreateResp::set_actor_entity_id(uint32_t value) {
  _internal_set_actor_entity_id(value);
  // @@protoc_insertion_point(field_set:PB.BattleInternal.BattleCreateResp.actor_entity_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace BattleInternal
}  // namespace PB

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::PB::BattleInternal::BattleCreateReq_MsgId> : ::std::true_type {};
template <> struct is_proto_enum< ::PB::BattleInternal::BattleCreateResp_MsgId> : ::std::true_type {};

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_game_5fbattle_2eproto
