// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game_battle.proto

#include "game_battle.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace PB {
namespace BattleInternal {
PROTOBUF_CONSTEXPR BattleCreateReq::BattleCreateReq(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.players_)*/{}
  , /*decltype(_impl_.battle_id_)*/0u
  , /*decltype(_impl_.map_id_)*/0
  , /*decltype(_impl_.requester_service_id_)*/0u
  , /*decltype(_impl_.requester_instance_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BattleCreateReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BattleCreateReqDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BattleCreateReqDefaultTypeInternal() {}
  union {
    BattleCreateReq _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BattleCreateReqDefaultTypeInternal _BattleCreateReq_default_instance_;
PROTOBUF_CONSTEXPR BattleCreateResp::BattleCreateResp(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.message_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.world_dump_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.code_)*/0
  , /*decltype(_impl_.battle_id_)*/0u
  , /*decltype(_impl_.battle_instance_id_)*/0u
  , /*decltype(_impl_.server_frame_)*/0u
  , /*decltype(_impl_.actor_entity_id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct BattleCreateRespDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BattleCreateRespDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~BattleCreateRespDefaultTypeInternal() {}
  union {
    BattleCreateResp _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BattleCreateRespDefaultTypeInternal _BattleCreateResp_default_instance_;
}  // namespace BattleInternal
}  // namespace PB
namespace PB {
namespace BattleInternal {
bool BattleCreateReq_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 60000:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> BattleCreateReq_MsgId_strings[2] = {};

static const char BattleCreateReq_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry BattleCreateReq_MsgId_entries[] = {
  { {BattleCreateReq_MsgId_names + 0, 2}, 60000 },
  { {BattleCreateReq_MsgId_names + 2, 4}, 0 },
};

static const int BattleCreateReq_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 60000 -> Id
};

const std::string& BattleCreateReq_MsgId_Name(
    BattleCreateReq_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          BattleCreateReq_MsgId_entries,
          BattleCreateReq_MsgId_entries_by_number,
          2, BattleCreateReq_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      BattleCreateReq_MsgId_entries,
      BattleCreateReq_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     BattleCreateReq_MsgId_strings[idx].get();
}
bool BattleCreateReq_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleCreateReq_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      BattleCreateReq_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<BattleCreateReq_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr BattleCreateReq_MsgId BattleCreateReq::None;
constexpr BattleCreateReq_MsgId BattleCreateReq::Id;
constexpr BattleCreateReq_MsgId BattleCreateReq::MsgId_MIN;
constexpr BattleCreateReq_MsgId BattleCreateReq::MsgId_MAX;
constexpr int BattleCreateReq::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
bool BattleCreateResp_MsgId_IsValid(int value) {
  switch (value) {
    case 0:
    case 60001:
      return true;
    default:
      return false;
  }
}

static ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<std::string> BattleCreateResp_MsgId_strings[2] = {};

static const char BattleCreateResp_MsgId_names[] =
  "Id"
  "None";

static const ::PROTOBUF_NAMESPACE_ID::internal::EnumEntry BattleCreateResp_MsgId_entries[] = {
  { {BattleCreateResp_MsgId_names + 0, 2}, 60001 },
  { {BattleCreateResp_MsgId_names + 2, 4}, 0 },
};

static const int BattleCreateResp_MsgId_entries_by_number[] = {
  1, // 0 -> None
  0, // 60001 -> Id
};

const std::string& BattleCreateResp_MsgId_Name(
    BattleCreateResp_MsgId value) {
  static const bool dummy =
      ::PROTOBUF_NAMESPACE_ID::internal::InitializeEnumStrings(
          BattleCreateResp_MsgId_entries,
          BattleCreateResp_MsgId_entries_by_number,
          2, BattleCreateResp_MsgId_strings);
  (void) dummy;
  int idx = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumName(
      BattleCreateResp_MsgId_entries,
      BattleCreateResp_MsgId_entries_by_number,
      2, value);
  return idx == -1 ? ::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString() :
                     BattleCreateResp_MsgId_strings[idx].get();
}
bool BattleCreateResp_MsgId_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, BattleCreateResp_MsgId* value) {
  int int_value;
  bool success = ::PROTOBUF_NAMESPACE_ID::internal::LookUpEnumValue(
      BattleCreateResp_MsgId_entries, 2, name, &int_value);
  if (success) {
    *value = static_cast<BattleCreateResp_MsgId>(int_value);
  }
  return success;
}
#if (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
constexpr BattleCreateResp_MsgId BattleCreateResp::None;
constexpr BattleCreateResp_MsgId BattleCreateResp::Id;
constexpr BattleCreateResp_MsgId BattleCreateResp::MsgId_MIN;
constexpr BattleCreateResp_MsgId BattleCreateResp::MsgId_MAX;
constexpr int BattleCreateResp::MsgId_ARRAYSIZE;
#endif  // (__cplusplus < 201703) && (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

// ===================================================================

class BattleCreateReq::_Internal {
 public:
};

void BattleCreateReq::clear_players() {
  _impl_.players_.Clear();
}
BattleCreateReq::BattleCreateReq(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.BattleInternal.BattleCreateReq)
}
BattleCreateReq::BattleCreateReq(const BattleCreateReq& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  BattleCreateReq* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.players_){from._impl_.players_}
    , decltype(_impl_.battle_id_){}
    , decltype(_impl_.map_id_){}
    , decltype(_impl_.requester_service_id_){}
    , decltype(_impl_.requester_instance_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  ::memcpy(&_impl_.battle_id_, &from._impl_.battle_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.requester_instance_id_) -
    reinterpret_cast<char*>(&_impl_.battle_id_)) + sizeof(_impl_.requester_instance_id_));
  // @@protoc_insertion_point(copy_constructor:PB.BattleInternal.BattleCreateReq)
}

inline void BattleCreateReq::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.players_){arena}
    , decltype(_impl_.battle_id_){0u}
    , decltype(_impl_.map_id_){0}
    , decltype(_impl_.requester_service_id_){0u}
    , decltype(_impl_.requester_instance_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

BattleCreateReq::~BattleCreateReq() {
  // @@protoc_insertion_point(destructor:PB.BattleInternal.BattleCreateReq)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BattleCreateReq::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.players_.~RepeatedPtrField();
}

void BattleCreateReq::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BattleCreateReq::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.BattleInternal.BattleCreateReq)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.players_.Clear();
  ::memset(&_impl_.battle_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.requester_instance_id_) -
      reinterpret_cast<char*>(&_impl_.battle_id_)) + sizeof(_impl_.requester_instance_id_));
  _internal_metadata_.Clear<std::string>();
}

const char* BattleCreateReq::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 battle_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.battle_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 map_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.map_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .PB.Types.BattlePlayerSpec players = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_players(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 requester_service_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.requester_service_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 requester_instance_id = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.requester_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BattleCreateReq::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.BattleInternal.BattleCreateReq)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 battle_id = 1;
  if (this->_internal_battle_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_battle_id(), target);
  }

  // int32 map_id = 2;
  if (this->_internal_map_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(2, this->_internal_map_id(), target);
  }

  // repeated .PB.Types.BattlePlayerSpec players = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_players_size()); i < n; i++) {
    const auto& repfield = this->_internal_players(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // uint32 requester_service_id = 4;
  if (this->_internal_requester_service_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_requester_service_id(), target);
  }

  // uint32 requester_instance_id = 5;
  if (this->_internal_requester_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_requester_instance_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.BattleInternal.BattleCreateReq)
  return target;
}

size_t BattleCreateReq::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.BattleInternal.BattleCreateReq)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .PB.Types.BattlePlayerSpec players = 3;
  total_size += 1UL * this->_internal_players_size();
  for (const auto& msg : this->_impl_.players_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint32 battle_id = 1;
  if (this->_internal_battle_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_battle_id());
  }

  // int32 map_id = 2;
  if (this->_internal_map_id() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_map_id());
  }

  // uint32 requester_service_id = 4;
  if (this->_internal_requester_service_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_requester_service_id());
  }

  // uint32 requester_instance_id = 5;
  if (this->_internal_requester_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_requester_instance_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BattleCreateReq::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const BattleCreateReq*>(
      &from));
}

void BattleCreateReq::MergeFrom(const BattleCreateReq& from) {
  BattleCreateReq* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.BattleInternal.BattleCreateReq)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.players_.MergeFrom(from._impl_.players_);
  if (from._internal_battle_id() != 0) {
    _this->_internal_set_battle_id(from._internal_battle_id());
  }
  if (from._internal_map_id() != 0) {
    _this->_internal_set_map_id(from._internal_map_id());
  }
  if (from._internal_requester_service_id() != 0) {
    _this->_internal_set_requester_service_id(from._internal_requester_service_id());
  }
  if (from._internal_requester_instance_id() != 0) {
    _this->_internal_set_requester_instance_id(from._internal_requester_instance_id());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void BattleCreateReq::CopyFrom(const BattleCreateReq& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.BattleInternal.BattleCreateReq)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleCreateReq::IsInitialized() const {
  return true;
}

void BattleCreateReq::InternalSwap(BattleCreateReq* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.players_.InternalSwap(&other->_impl_.players_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BattleCreateReq, _impl_.requester_instance_id_)
      + sizeof(BattleCreateReq::_impl_.requester_instance_id_)
      - PROTOBUF_FIELD_OFFSET(BattleCreateReq, _impl_.battle_id_)>(
          reinterpret_cast<char*>(&_impl_.battle_id_),
          reinterpret_cast<char*>(&other->_impl_.battle_id_));
}

std::string BattleCreateReq::GetTypeName() const {
  return "PB.BattleInternal.BattleCreateReq";
}


// ===================================================================

class BattleCreateResp::_Internal {
 public:
};

BattleCreateResp::BattleCreateResp(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:PB.BattleInternal.BattleCreateResp)
}
BattleCreateResp::BattleCreateResp(const BattleCreateResp& from)
  : ::PROTOBUF_NAMESPACE_ID::MessageLite() {
  BattleCreateResp* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.world_dump_){}
    , decltype(_impl_.code_){}
    , decltype(_impl_.battle_id_){}
    , decltype(_impl_.battle_instance_id_){}
    , decltype(_impl_.server_frame_){}
    , decltype(_impl_.actor_entity_id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    _this->_impl_.message_.Set(from._internal_message(), 
      _this->GetArenaForAllocation());
  }
  _impl_.world_dump_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.world_dump_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_world_dump().empty()) {
    _this->_impl_.world_dump_.Set(from._internal_world_dump(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.code_, &from._impl_.code_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.actor_entity_id_) -
    reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.actor_entity_id_));
  // @@protoc_insertion_point(copy_constructor:PB.BattleInternal.BattleCreateResp)
}

inline void BattleCreateResp::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.message_){}
    , decltype(_impl_.world_dump_){}
    , decltype(_impl_.code_){0}
    , decltype(_impl_.battle_id_){0u}
    , decltype(_impl_.battle_instance_id_){0u}
    , decltype(_impl_.server_frame_){0u}
    , decltype(_impl_.actor_entity_id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.world_dump_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.world_dump_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

BattleCreateResp::~BattleCreateResp() {
  // @@protoc_insertion_point(destructor:PB.BattleInternal.BattleCreateResp)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<std::string>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void BattleCreateResp::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.message_.Destroy();
  _impl_.world_dump_.Destroy();
}

void BattleCreateResp::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void BattleCreateResp::Clear() {
// @@protoc_insertion_point(message_clear_start:PB.BattleInternal.BattleCreateResp)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _impl_.world_dump_.ClearToEmpty();
  ::memset(&_impl_.code_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.actor_entity_id_) -
      reinterpret_cast<char*>(&_impl_.code_)) + sizeof(_impl_.actor_entity_id_));
  _internal_metadata_.Clear<std::string>();
}

const char* BattleCreateResp::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, nullptr));
        } else
          goto handle_unusual;
        continue;
      // uint32 battle_id = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _impl_.battle_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 battle_instance_id = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 32)) {
          _impl_.battle_instance_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 server_frame = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 40)) {
          _impl_.server_frame_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes world_dump = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 50)) {
          auto str = _internal_mutable_world_dump();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 actor_entity_id = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.actor_entity_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<std::string>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* BattleCreateResp::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:PB.BattleInternal.BattleCreateResp)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "PB.BattleInternal.BattleCreateResp.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // uint32 battle_id = 3;
  if (this->_internal_battle_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(3, this->_internal_battle_id(), target);
  }

  // uint32 battle_instance_id = 4;
  if (this->_internal_battle_instance_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(4, this->_internal_battle_instance_id(), target);
  }

  // uint32 server_frame = 5;
  if (this->_internal_server_frame() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(5, this->_internal_server_frame(), target);
  }

  // bytes world_dump = 6;
  if (!this->_internal_world_dump().empty()) {
    target = stream->WriteBytesMaybeAliased(
        6, this->_internal_world_dump(), target);
  }

  // uint32 actor_entity_id = 7;
  if (this->_internal_actor_entity_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(7, this->_internal_actor_entity_id(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).data(),
        static_cast<int>(_internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PB.BattleInternal.BattleCreateResp)
  return target;
}

size_t BattleCreateResp::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PB.BattleInternal.BattleCreateResp)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // bytes world_dump = 6;
  if (!this->_internal_world_dump().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_world_dump());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  // uint32 battle_id = 3;
  if (this->_internal_battle_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_battle_id());
  }

  // uint32 battle_instance_id = 4;
  if (this->_internal_battle_instance_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_battle_instance_id());
  }

  // uint32 server_frame = 5;
  if (this->_internal_server_frame() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_server_frame());
  }

  // uint32 actor_entity_id = 7;
  if (this->_internal_actor_entity_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_actor_entity_id());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    total_size += _internal_metadata_.unknown_fields<std::string>(::PROTOBUF_NAMESPACE_ID::internal::GetEmptyString).size();
  }
  int cached_size = ::_pbi::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BattleCreateResp::CheckTypeAndMergeFrom(
    const ::PROTOBUF_NAMESPACE_ID::MessageLite& from) {
  MergeFrom(*::_pbi::DownCast<const BattleCreateResp*>(
      &from));
}

void BattleCreateResp::MergeFrom(const BattleCreateResp& from) {
  BattleCreateResp* const _this = this;
  // @@protoc_insertion_point(class_specific_merge_from_start:PB.BattleInternal.BattleCreateResp)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  if (!from._internal_world_dump().empty()) {
    _this->_internal_set_world_dump(from._internal_world_dump());
  }
  if (from._internal_code() != 0) {
    _this->_internal_set_code(from._internal_code());
  }
  if (from._internal_battle_id() != 0) {
    _this->_internal_set_battle_id(from._internal_battle_id());
  }
  if (from._internal_battle_instance_id() != 0) {
    _this->_internal_set_battle_instance_id(from._internal_battle_instance_id());
  }
  if (from._internal_server_frame() != 0) {
    _this->_internal_set_server_frame(from._internal_server_frame());
  }
  if (from._internal_actor_entity_id() != 0) {
    _this->_internal_set_actor_entity_id(from._internal_actor_entity_id());
  }
  _this->_internal_metadata_.MergeFrom<std::string>(from._internal_metadata_);
}

void BattleCreateResp::CopyFrom(const BattleCreateResp& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PB.BattleInternal.BattleCreateResp)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleCreateResp::IsInitialized() const {
  return true;
}

void BattleCreateResp::InternalSwap(BattleCreateResp* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.message_, lhs_arena,
      &other->_impl_.message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.world_dump_, lhs_arena,
      &other->_impl_.world_dump_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(BattleCreateResp, _impl_.actor_entity_id_)
      + sizeof(BattleCreateResp::_impl_.actor_entity_id_)
      - PROTOBUF_FIELD_OFFSET(BattleCreateResp, _impl_.code_)>(
          reinterpret_cast<char*>(&_impl_.code_),
          reinterpret_cast<char*>(&other->_impl_.code_));
}

std::string BattleCreateResp::GetTypeName() const {
  return "PB.BattleInternal.BattleCreateResp";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace BattleInternal
}  // namespace PB
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::PB::BattleInternal::BattleCreateReq*
Arena::CreateMaybeMessage< ::PB::BattleInternal::BattleCreateReq >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::BattleInternal::BattleCreateReq >(arena);
}
template<> PROTOBUF_NOINLINE ::PB::BattleInternal::BattleCreateResp*
Arena::CreateMaybeMessage< ::PB::BattleInternal::BattleCreateResp >(Arena* arena) {
  return Arena::CreateMessageInternal< ::PB::BattleInternal::BattleCreateResp >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
