// This file is @generated by prost-build.
/// Game 发给 Battle，请求创建一场战斗。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleCreateReq {
    /// 战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 地图 id。
    #[prost(int32, tag = "2")]
    pub map_id: i32,
    /// 参战玩家。
    #[prost(message, repeated, tag = "3")]
    pub players: ::prost::alloc::vec::Vec<super::types::BattlePlayerSpec>,
    /// 旧字段暂时保留，跨服来源以 ForwardToServerReq 为准。
    #[prost(uint32, tag = "4")]
    pub requester_service_id: u32,
    /// 旧字段暂时保留，跨服来源以 ForwardToServerReq 为准。
    #[prost(uint32, tag = "5")]
    pub requester_instance_id: u32,
    /// 战斗世界随机种子（由 game 生成，battle/客户端共用）。
    #[prost(uint64, tag = "6")]
    pub random_seed: u64,
}
/// Nested message and enum types in `BattleCreateReq`.
pub mod battle_create_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 60000,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// Battle 返回创建战斗结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleCreateResp {
    /// 创建结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 战斗 id。
    #[prost(uint32, tag = "3")]
    pub battle_id: u32,
    /// 承载这场战斗的 battle 实例 id。
    #[prost(uint32, tag = "4")]
    pub battle_instance_id: u32,
    /// 当前服务器帧。
    #[prost(uint32, tag = "5")]
    pub server_frame: u32,
    /// 战斗世界快照。
    #[prost(bytes = "vec", tag = "6")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
    /// 请求方 session 对应的 actor 实体 id，便于客户端绑定 localPlayer。
    #[prost(uint32, tag = "7")]
    pub actor_entity_id: u32,
    /// 所有已加入玩家的 actor 映射（决斗等多人场景使用）。
    #[prost(message, repeated, tag = "8")]
    pub players: ::prost::alloc::vec::Vec<BattlePlayerSpawn>,
}
/// Nested message and enum types in `BattleCreateResp`.
pub mod battle_create_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 60001,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 单个已加入玩家的 actor 映射。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattlePlayerSpawn {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 对应的 actor 实体 id。
    #[prost(uint32, tag = "2")]
    pub actor_entity_id: u32,
}
