// This file is @generated by prost-build.
/// 客户端战斗输入。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleInputPush {
    /// 战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 客户端帧号。
    #[prost(uint32, tag = "2")]
    pub client_frame: u32,
    /// 输入按键位。
    #[prost(uint32, tag = "3")]
    pub input_mask: u32,
    /// 客户端时间戳，毫秒。
    #[prost(uint64, tag = "4")]
    pub client_time_ms: u64,
}
/// Nested message and enum types in `BattleInputPush`.
pub mod battle_input_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 20012,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 战斗服下发的战斗快照。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleSnapshotPush {
    /// 战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 服务器帧号。
    #[prost(uint32, tag = "2")]
    pub server_frame: u32,
    /// 服务器时间戳，毫秒。
    #[prost(uint64, tag = "3")]
    pub server_time_ms: u64,
    /// 战斗世界快照。
    #[prost(bytes = "vec", tag = "4")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `BattleSnapshotPush`.
pub mod battle_snapshot_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 20013,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
