// This file is @generated by prost-build.
/// 通用成功响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonSuccessResp {
    /// 结果码，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CommonSuccessResp`.
pub mod common_success_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 900,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 通用错误响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonErrorResp {
    /// 错误码。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 错误说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CommonErrorResp`.
pub mod common_error_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 901,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 登录请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginReq {
    /// 账号名。
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    /// 密码。
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// Nested message and enum types in `LoginReq`.
pub mod login_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1000,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 登录响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResp {
    /// 登录结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 玩家 id。
    #[prost(int64, tag = "3")]
    pub player_id: i64,
    /// 玩家昵称。
    #[prost(string, tag = "4")]
    pub nickname: ::prost::alloc::string::String,
    /// 登录后下发的服务器配置。
    #[prost(message, optional, tag = "5")]
    pub server_config: ::core::option::Option<ServerConfig>,
    /// 登录账号信息。
    #[prost(message, optional, tag = "6")]
    pub account_info: ::core::option::Option<AccountInfo>,
}
/// Nested message and enum types in `LoginResp`.
pub mod login_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1001,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 注册请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterReq {
    /// 账号名。
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    /// 密码。
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// 昵称。
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
}
/// Nested message and enum types in `RegisterReq`.
pub mod register_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1002,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 注册响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResp {
    /// 注册结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 新建玩家 id。
    #[prost(int64, tag = "3")]
    pub player_id: i64,
}
/// Nested message and enum types in `RegisterResp`.
pub mod register_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1003,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 登录后下发的服务器配置。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerConfig {
    /// 最大角色数量。
    #[prost(int32, tag = "1")]
    pub max_character_count: i32,
}
/// 登录账号信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountInfo {
    /// 玩家 id。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// 账号名。
    #[prost(string, tag = "2")]
    pub account: ::prost::alloc::string::String,
    /// 昵称。
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
}
/// 装备上的一条附魔属性。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnchantProp {
    /// 属性配置 id。
    #[prost(int32, tag = "1")]
    pub attr_id: i32,
    /// 属性值。
    #[prost(int32, tag = "2")]
    pub value: i32,
}
/// 装备信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EquipmentInfo {
    /// 装备实例 id。
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 装备配置 id。
    #[prost(int64, tag = "2")]
    pub config_id: i64,
    /// 强化等级。
    #[prost(int32, tag = "3")]
    pub enhance_level: i32,
    /// 精炼等级。
    #[prost(int32, tag = "4")]
    pub refine_level: i32,
    /// 附魔属性列表。
    #[prost(message, repeated, tag = "5")]
    pub enchant_props: ::prost::alloc::vec::Vec<EnchantProp>,
    /// 装备槽位。
    #[prost(int32, tag = "6")]
    pub slot: i32,
}
/// 普通道具信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemInfo {
    /// 道具实例 id。
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 道具配置 id。
    #[prost(int64, tag = "2")]
    pub config_id: i64,
    /// 数量。
    #[prost(int32, tag = "3")]
    pub count: i32,
}
/// 背包信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryInfo {
    /// 普通道具列表。
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ItemInfo>,
    /// 装备列表。
    #[prost(message, repeated, tag = "2")]
    pub equipments: ::prost::alloc::vec::Vec<EquipmentInfo>,
}
/// 角色信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterInfo {
    /// 角色 id。
    #[prost(int64, tag = "1")]
    pub character_id: i64,
    /// 角色名。
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 职业 id。
    #[prost(int32, tag = "3")]
    pub class_id: i32,
    /// 性别。
    #[prost(int32, tag = "4")]
    pub gender: i32,
    /// 等级。
    #[prost(int32, tag = "5")]
    pub level: i32,
    /// 经验。
    #[prost(int64, tag = "6")]
    pub exp: i64,
    /// 金币。
    #[prost(int64, tag = "7")]
    pub gold: i64,
}
/// 玩家基础信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInfo {
    /// 玩家 id。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// 昵称。
    #[prost(string, tag = "2")]
    pub nickname: ::prost::alloc::string::String,
    /// 等级。
    #[prost(int32, tag = "3")]
    pub level: i32,
    /// 经验。
    #[prost(int64, tag = "4")]
    pub exp: i64,
}
/// Nested message and enum types in `PlayerInfo`.
pub mod player_info {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1100,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 创建角色请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCharacterReq {
    /// 角色名。
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 职业 id。
    #[prost(int32, tag = "2")]
    pub class_id: i32,
    /// 性别。
    #[prost(int32, tag = "3")]
    pub gender: i32,
}
/// Nested message and enum types in `CreateCharacterReq`.
pub mod create_character_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1200,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 创建角色响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCharacterResp {
    /// 创建结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 创建成功后的角色信息。
    #[prost(message, optional, tag = "3")]
    pub character: ::core::option::Option<CharacterInfo>,
}
/// Nested message and enum types in `CreateCharacterResp`.
pub mod create_character_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1201,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 拉取角色列表请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchCharacterListReq {}
/// Nested message and enum types in `FetchCharacterListReq`.
pub mod fetch_character_list_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1202,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 拉取角色列表响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchCharacterListResp {
    /// 拉取结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 角色列表。
    #[prost(message, repeated, tag = "3")]
    pub characters: ::prost::alloc::vec::Vec<CharacterInfo>,
}
/// Nested message and enum types in `FetchCharacterListResp`.
pub mod fetch_character_list_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1203,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 选择角色请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCharacterReq {
    /// 要进入游戏的角色 id。
    #[prost(int64, tag = "1")]
    pub character_id: i64,
}
/// Nested message and enum types in `SelectCharacterReq`.
pub mod select_character_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1204,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 选择角色响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCharacterResp {
    /// 选择结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 当前角色信息。
    #[prost(message, optional, tag = "3")]
    pub character: ::core::option::Option<CharacterInfo>,
    /// 当前角色背包。
    #[prost(message, optional, tag = "4")]
    pub inventory: ::core::option::Option<InventoryInfo>,
}
/// Nested message and enum types in `SelectCharacterResp`.
pub mod select_character_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1205,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 帧同步里用到的玩家状态。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerState {
    /// 玩家 id。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// x 坐标。
    #[prost(float, tag = "2")]
    pub pos_x: f32,
    /// y 坐标。
    #[prost(float, tag = "3")]
    pub pos_y: f32,
    /// 当前血量。
    #[prost(int32, tag = "4")]
    pub hp: i32,
    /// 当前状态。
    #[prost(string, tag = "5")]
    pub state: ::prost::alloc::string::String,
}
/// Nested message and enum types in `PlayerState`.
pub mod player_state {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 20000,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 客户端请求进入战斗。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleJoinReq {
    /// 玩家 id。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// 地图 id。
    #[prost(int32, tag = "2")]
    pub map_id: i32,
}
/// Nested message and enum types in `BattleJoinReq`.
pub mod battle_join_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1300,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 进入战斗响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleJoinResp {
    /// 进入结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 战斗 id。
    #[prost(uint32, tag = "3")]
    pub battle_id: u32,
    /// 当前服务器帧。
    #[prost(uint32, tag = "4")]
    pub server_frame: u32,
    /// 战斗世界快照。
    #[prost(bytes = "vec", tag = "5")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `BattleJoinResp`.
pub mod battle_join_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1301,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 创建战斗时传给战斗服的玩家信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattlePlayerSpec {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 玩家 id。
    #[prost(int64, tag = "2")]
    pub player_id: i64,
}
/// Game 发给 Battle，请求创建一场战斗。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleCreateReq {
    /// 战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 地图 id。
    #[prost(int32, tag = "2")]
    pub map_id: i32,
    /// 参战玩家。
    #[prost(message, repeated, tag = "3")]
    pub players: ::prost::alloc::vec::Vec<BattlePlayerSpec>,
    /// 旧字段暂时保留，跨服来源以 ForwardToServerReq 为准。
    #[prost(uint32, tag = "4")]
    pub requester_service_id: u32,
    /// 旧字段暂时保留，跨服来源以 ForwardToServerReq 为准。
    #[prost(uint32, tag = "5")]
    pub requester_instance_id: u32,
}
/// Nested message and enum types in `BattleCreateReq`.
pub mod battle_create_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 20014,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// Battle 返回创建战斗结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleCreateResp {
    /// 创建结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 战斗 id。
    #[prost(uint32, tag = "3")]
    pub battle_id: u32,
    /// 承载这场战斗的 battle 实例 id。
    #[prost(uint32, tag = "4")]
    pub battle_instance_id: u32,
    /// 当前服务器帧。
    #[prost(uint32, tag = "5")]
    pub server_frame: u32,
    /// 战斗世界快照。
    #[prost(bytes = "vec", tag = "6")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `BattleCreateResp`.
pub mod battle_create_resp {
    /// 创建战斗响应的消息号。
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        /// 无效消息号。
        None = 0,
        /// 创建战斗响应。
        Id = 20015,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 客户端战斗输入。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleInputPush {
    /// 战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 客户端帧号。
    #[prost(uint32, tag = "2")]
    pub client_frame: u32,
    /// 输入按键位。
    #[prost(uint32, tag = "3")]
    pub input_mask: u32,
    /// 客户端时间戳，毫秒。
    #[prost(uint64, tag = "4")]
    pub client_time_ms: u64,
}
/// Nested message and enum types in `BattleInputPush`.
pub mod battle_input_push {
    /// 战斗输入的消息号。
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        /// 无效消息号。
        None = 0,
        /// 战斗输入。
        Id = 20012,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 战斗服下发的战斗快照。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleSnapshotPush {
    /// 战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 服务器帧号。
    #[prost(uint32, tag = "2")]
    pub server_frame: u32,
    /// 服务器时间戳，毫秒。
    #[prost(uint64, tag = "3")]
    pub server_time_ms: u64,
    /// 战斗世界快照。
    #[prost(bytes = "vec", tag = "4")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
/// Nested message and enum types in `BattleSnapshotPush`.
pub mod battle_snapshot_push {
    /// 战斗快照的消息号。
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        /// 无效消息号。
        None = 0,
        /// 战斗快照。
        Id = 20013,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 账号在别处登录，服务器主动通知当前客户端下线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountKickedPush {
    /// 原因码，1 表示账号在别处登录。
    #[prost(int32, tag = "1")]
    pub reason: i32,
    /// 下线说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `AccountKickedPush`.
pub mod account_kicked_push {
    /// 账号踢下线通知的消息号。
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        /// 无效消息号。
        None = 0,
        /// 账号踢下线通知。
        Id = 20016,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 玩家所在战斗服下线时由 game 服推给客户端。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleServerOfflinePush {
    /// 受影响的战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 下线的 battle 实例 id。
    #[prost(uint32, tag = "2")]
    pub battle_instance_id: u32,
    /// 原因码，1 表示后端服务下线。
    #[prost(int32, tag = "3")]
    pub reason: i32,
    /// 下线说明。
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `BattleServerOfflinePush`.
pub mod battle_server_offline_push {
    /// 战斗服下线通知的消息号。
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        /// 无效消息号。
        None = 0,
        /// 战斗服下线通知。
        Id = 20017,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 玩家所在城镇服下线时由 game 服推给客户端。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TownServerOfflinePush {
    /// 下线的 town 实例 id。
    #[prost(uint32, tag = "1")]
    pub town_instance_id: u32,
    /// 原因码，1 表示后端服务下线。
    #[prost(int32, tag = "2")]
    pub reason: i32,
    /// 下线说明。
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `TownServerOfflinePush`.
pub mod town_server_offline_push {
    /// 城镇服下线通知的消息号。
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        /// 无效消息号。
        None = 0,
        /// 城镇服下线通知。
        Id = 20018,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
