// This file is @generated by prost-build.
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonSuccessResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 900; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonErrorResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 901; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 登录。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1000; }
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1001; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub player_id: i64,
    #[prost(string, tag = "4")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub server_config: ::core::option::Option<ServerConfig>,
    #[prost(message, optional, tag = "6")]
    pub account_info: ::core::option::Option<AccountInfo>,
}
/// 注册。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1002; }
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1003; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub player_id: i64,
}
/// 登录后下发的服务器配置。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerConfig {
    #[prost(int32, tag = "1")]
    pub max_character_count: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountInfo {
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    #[prost(string, tag = "2")]
    pub account: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnchantProp {
    #[prost(int32, tag = "1")]
    pub attr_id: i32,
    #[prost(int32, tag = "2")]
    pub value: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EquipmentInfo {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub config_id: i64,
    #[prost(int32, tag = "3")]
    pub enhance_level: i32,
    #[prost(int32, tag = "4")]
    pub refine_level: i32,
    #[prost(message, repeated, tag = "5")]
    pub enchant_props: ::prost::alloc::vec::Vec<EnchantProp>,
    #[prost(int32, tag = "6")]
    pub slot: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemInfo {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(int64, tag = "2")]
    pub config_id: i64,
    #[prost(int32, tag = "3")]
    pub count: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryInfo {
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ItemInfo>,
    #[prost(message, repeated, tag = "2")]
    pub equipments: ::prost::alloc::vec::Vec<EquipmentInfo>,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterInfo {
    #[prost(int64, tag = "1")]
    pub character_id: i64,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub class_id: i32,
    #[prost(int32, tag = "4")]
    pub gender: i32,
    #[prost(int32, tag = "5")]
    pub level: i32,
    #[prost(int64, tag = "6")]
    pub exp: i64,
    #[prost(int64, tag = "7")]
    pub gold: i64,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInfo {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1100; }
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    #[prost(string, tag = "2")]
    pub nickname: ::prost::alloc::string::String,
    #[prost(int32, tag = "3")]
    pub level: i32,
    #[prost(int64, tag = "4")]
    pub exp: i64,
}
/// 创建角色。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCharacterReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1200; }
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag = "2")]
    pub class_id: i32,
    #[prost(int32, tag = "3")]
    pub gender: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCharacterResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1201; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub character: ::core::option::Option<CharacterInfo>,
}
/// 拉取角色列表。
///
/// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1202; }
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchCharacterListReq {}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchCharacterListResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1203; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub characters: ::prost::alloc::vec::Vec<CharacterInfo>,
}
/// 选择角色进入游戏。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCharacterReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1204; }
    #[prost(int64, tag = "1")]
    pub character_id: i64,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCharacterResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1205; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub character: ::core::option::Option<CharacterInfo>,
    #[prost(message, optional, tag = "4")]
    pub inventory: ::core::option::Option<InventoryInfo>,
}
/// 帧同步里用到的玩家状态。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerState {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20000; }
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    #[prost(float, tag = "2")]
    pub pos_x: f32,
    #[prost(float, tag = "3")]
    pub pos_y: f32,
    #[prost(int32, tag = "4")]
    pub hp: i32,
    #[prost(string, tag = "5")]
    pub state: ::prost::alloc::string::String,
}
/// 客户端请求进入副本战斗。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleJoinReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20010; }
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    #[prost(int32, tag = "2")]
    pub map_id: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleJoinResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20011; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub battle_id: u32,
    #[prost(uint32, tag = "4")]
    pub server_frame: u32,
    #[prost(bytes = "vec", tag = "5")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattlePlayerSpec {
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(int64, tag = "2")]
    pub player_id: i64,
}
/// Game 发给 Battle，要求创建一场战斗。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleCreateReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20014; }
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    #[prost(int32, tag = "2")]
    pub map_id: i32,
    #[prost(message, repeated, tag = "3")]
    pub players: ::prost::alloc::vec::Vec<BattlePlayerSpec>,
    /// 旧字段暂时保留，跨服来源以 ForwardToServerReq 为准。
    #[prost(uint32, tag = "4")]
    pub requester_service_id: u32,
    #[prost(uint32, tag = "5")]
    pub requester_instance_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleCreateResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20015; }
    #[prost(int32, tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub battle_id: u32,
    #[prost(uint32, tag = "4")]
    pub battle_instance_id: u32,
    #[prost(uint32, tag = "5")]
    pub server_frame: u32,
    #[prost(bytes = "vec", tag = "6")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleInputPush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20012; }
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    #[prost(uint32, tag = "2")]
    pub client_frame: u32,
    #[prost(uint32, tag = "3")]
    pub input_mask: u32,
    #[prost(uint64, tag = "4")]
    pub client_time_ms: u64,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleSnapshotPush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 20013; }
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    #[prost(uint32, tag = "2")]
    pub server_frame: u32,
    #[prost(uint64, tag = "3")]
    pub server_time_ms: u64,
    #[prost(bytes = "vec", tag = "4")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
}
