// This file is @generated by prost-build.
/// 通用成功响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonSuccessResp {
    /// 结果码，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CommonSuccessResp`.
pub mod common_success_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 900,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 通用错误响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommonErrorResp {
    /// 错误码。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 错误说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `CommonErrorResp`.
pub mod common_error_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 901,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 登录请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginReq {
    /// 账号名。
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    /// 密码。
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// Nested message and enum types in `LoginReq`.
pub mod login_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1000,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 登录响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResp {
    /// 登录结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 玩家 id。
    #[prost(int64, tag = "3")]
    pub player_id: i64,
    /// 玩家昵称。
    #[prost(string, tag = "4")]
    pub nickname: ::prost::alloc::string::String,
    /// 登录后下发的服务器配置。
    #[prost(message, optional, tag = "5")]
    pub server_config: ::core::option::Option<super::types::ServerConfig>,
    /// 登录账号信息。
    #[prost(message, optional, tag = "6")]
    pub account_info: ::core::option::Option<super::types::AccountInfo>,
}
/// Nested message and enum types in `LoginResp`.
pub mod login_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1001,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 注册请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterReq {
    /// 账号名。
    #[prost(string, tag = "1")]
    pub account: ::prost::alloc::string::String,
    /// 密码。
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// 昵称。
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
}
/// Nested message and enum types in `RegisterReq`.
pub mod register_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1002,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 注册响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResp {
    /// 注册结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 新建玩家 id。
    #[prost(int64, tag = "3")]
    pub player_id: i64,
}
/// Nested message and enum types in `RegisterResp`.
pub mod register_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1003,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 玩家基础信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerInfo {
    /// 玩家 id。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// 昵称。
    #[prost(string, tag = "2")]
    pub nickname: ::prost::alloc::string::String,
    /// 等级。
    #[prost(int32, tag = "3")]
    pub level: i32,
    /// 经验。
    #[prost(int64, tag = "4")]
    pub exp: i64,
}
/// Nested message and enum types in `PlayerInfo`.
pub mod player_info {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1100,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 创建角色请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCharacterReq {
    /// 角色名。
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 职业 id。
    #[prost(int32, tag = "2")]
    pub class_id: i32,
    /// 性别。
    #[prost(int32, tag = "3")]
    pub gender: i32,
}
/// Nested message and enum types in `CreateCharacterReq`.
pub mod create_character_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1200,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 创建角色响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateCharacterResp {
    /// 创建结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 创建成功后的角色信息。
    #[prost(message, optional, tag = "3")]
    pub character: ::core::option::Option<super::types::CharacterInfo>,
}
/// Nested message and enum types in `CreateCharacterResp`.
pub mod create_character_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1201,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 拉取角色列表请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchCharacterListReq {}
/// Nested message and enum types in `FetchCharacterListReq`.
pub mod fetch_character_list_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1202,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 拉取角色列表响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FetchCharacterListResp {
    /// 拉取结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 角色列表。
    #[prost(message, repeated, tag = "3")]
    pub characters: ::prost::alloc::vec::Vec<super::types::CharacterInfo>,
}
/// Nested message and enum types in `FetchCharacterListResp`.
pub mod fetch_character_list_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1203,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 选择角色请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCharacterReq {
    /// 要进入游戏的角色 id。
    #[prost(int64, tag = "1")]
    pub character_id: i64,
}
/// Nested message and enum types in `SelectCharacterReq`.
pub mod select_character_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1204,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 选择角色响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectCharacterResp {
    /// 选择结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 当前角色信息。
    #[prost(message, optional, tag = "3")]
    pub character: ::core::option::Option<super::types::CharacterInfo>,
    /// 当前角色背包。
    #[prost(message, optional, tag = "4")]
    pub inventory: ::core::option::Option<super::types::InventoryInfo>,
}
/// Nested message and enum types in `SelectCharacterResp`.
pub mod select_character_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1205,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 客户端请求进入战斗。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleJoinReq {
    /// 玩家 id。服务端实际以登录态为准。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// 地图 id。
    #[prost(int32, tag = "2")]
    pub map_id: i32,
}
/// Nested message and enum types in `BattleJoinReq`.
pub mod battle_join_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1300,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 进入战斗响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleJoinResp {
    /// 进入结果，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 战斗 id。
    #[prost(uint32, tag = "3")]
    pub battle_id: u32,
    /// 当前服务器帧。
    #[prost(uint32, tag = "4")]
    pub server_frame: u32,
    /// 战斗世界快照。
    #[prost(bytes = "vec", tag = "5")]
    pub world_dump: ::prost::alloc::vec::Vec<u8>,
    /// 本机对应的 actor 实体 id，用于绑定 localPlayer。
    #[prost(uint32, tag = "6")]
    pub actor_entity_id: u32,
}
/// Nested message and enum types in `BattleJoinResp`.
pub mod battle_join_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1301,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 客户端请求进入城镇场景。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnterSceneReq {
    /// 要进入的目标类型。
    #[prost(enumeration = "super::types::SceneEnterType", tag = "1")]
    pub r#type: i32,
    /// 普通地图 id，type 为 Map 时填写。
    #[prost(uint32, tag = "2")]
    pub map_id: u32,
    /// 家园拥有者玩家 id，type 为 Home 时填写。
    #[prost(uint64, tag = "3")]
    pub owner_uid: u64,
    /// 客户端当前上报的玩家状态，player_id 由服务器登录态覆盖。
    #[prost(message, optional, tag = "4")]
    pub state: ::core::option::Option<super::types::PlayerState>,
}
/// Nested message and enum types in `EnterSceneReq`.
pub mod enter_scene_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1302,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// game 服返回给客户端的进入城镇场景结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnterSceneResp {
    /// 结果码，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 当前场景公开信息，不包含 SceneId。
    #[prost(message, optional, tag = "3")]
    pub scene: ::core::option::Option<super::types::SceneInfo>,
    /// 当前场景内的玩家状态快照，包含自己。
    #[prost(message, repeated, tag = "4")]
    pub players: ::prost::alloc::vec::Vec<super::types::PlayerState>,
}
/// Nested message and enum types in `EnterSceneResp`.
pub mod enter_scene_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1303,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 账号在别处登录，服务器主动通知当前客户端下线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountKickedPush {
    /// 原因码，1 表示账号在别处登录。
    #[prost(int32, tag = "1")]
    pub reason: i32,
    /// 下线说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `AccountKickedPush`.
pub mod account_kicked_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1400,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 玩家所在战斗服下线时由 game 服推给客户端。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattleServerOfflinePush {
    /// 受影响的战斗 id。
    #[prost(uint32, tag = "1")]
    pub battle_id: u32,
    /// 下线的 battle 实例 id。
    #[prost(uint32, tag = "2")]
    pub battle_instance_id: u32,
    /// 原因码，1 表示后端服务下线。
    #[prost(int32, tag = "3")]
    pub reason: i32,
    /// 下线说明。
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `BattleServerOfflinePush`.
pub mod battle_server_offline_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1401,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 玩家所在城镇服下线时由 game 服推给客户端。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TownServerOfflinePush {
    /// 下线的 town 实例 id。
    #[prost(uint32, tag = "1")]
    pub town_instance_id: u32,
    /// 原因码，1 表示后端服务下线。
    #[prost(int32, tag = "2")]
    pub reason: i32,
    /// 下线说明。
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `TownServerOfflinePush`.
pub mod town_server_offline_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 1402,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
