// This file is @generated by prost-build.
/// 单个后端服务实例的状态。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceStatus {
    /// 服务类型，例如 game=0、battle=1。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 ID。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
    /// 是否在线。
    #[prost(bool, tag = "3")]
    pub online: bool,
}
/// 网关推送给客户端的服务状态快照。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusPush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1; }
    /// 当前在线服务实例列表。
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<ServiceStatus>,
}
/// 网关返回给客户端的错误响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GatewayErrorResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 2; }
    /// 错误码。
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 错误说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 后端服务实例地址描述。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceEndpoint {
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 ID。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 后端服务连接网关后的注册请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 3; }
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 ID。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 网关返回给后端服务的注册结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 4; }
    /// 0 表示成功，非 0 表示失败。
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 注册前已经在线的服务实例列表。
    #[prost(message, repeated, tag = "2")]
    pub servers: ::prost::alloc::vec::Vec<ServiceEndpoint>,
}
/// 后端请求网关将客户端会话绑定到某类服务实例。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 5; }
    /// 客户端会话 ID。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 要绑定的服务类型。
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    /// 目标服务实例 ID；小于 0 表示由网关自动选择。
    #[prost(int32, tag = "3")]
    pub target_instance_id: i32,
}
/// 后端请求网关取消客户端会话和某类服务的绑定。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 6; }
    /// 客户端会话 ID。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 要取消绑定的服务类型。
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
}
/// 后端请求网关断开某个客户端会话。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickSessionReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 7; }
    /// 客户端会话 ID。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// 网关通知后端：客户端会话已上线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOnlinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 8; }
    /// 客户端会话 ID。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// 网关通知后端：客户端会话已下线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOfflinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 9; }
    /// 客户端会话 ID。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// 网关通知后端：某个服务实例已上线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOnlinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 10; }
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 ID。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 网关通知后端：某个服务实例已下线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOfflinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 11; }
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 ID。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 后端请求网关将已封装好的后端帧转发给指定服务实例。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardToServerReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 12; }
    /// 目标服务类型。
    #[prost(uint32, tag = "1")]
    pub target_service_id: u32,
    /// 目标服务实例 ID。
    #[prost(uint32, tag = "2")]
    pub target_instance_id: u32,
    /// 要转发的完整后端帧 payload。
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
}
