// This file is @generated by prost-build.
/// 后端服务在线状态。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceStatus {
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
    #[prost(bool, tag = "3")]
    pub online: bool,
}
/// 当前可见的后端服务列表。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusPush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 1; }
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<ServiceStatus>,
}
/// 网关给客户端的错误响应。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GatewayErrorResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 2; }
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceEndpoint {
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 后端连上网关后的注册消息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 3; }
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
    /// 注册时带上初始负载，避免首次选择缺数据。
    #[prost(uint32, tag = "3")]
    pub load_score: u32,
    #[prost(bool, tag = "4")]
    pub accepting_bindings: bool,
    #[prost(string, tag = "5")]
    pub load_message: ::prost::alloc::string::String,
}
/// 网关返回注册结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 4; }
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(message, repeated, tag = "2")]
    pub servers: ::prost::alloc::vec::Vec<ServiceEndpoint>,
}
/// 把客户端会话绑定到某类后端服务。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 5; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    /// 小于 0 时由网关选择最低负载实例。
    #[prost(int32, tag = "3")]
    pub target_instance_id: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 6; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 17; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    /// 0=OK.
    #[prost(uint32, tag = "3")]
    pub code: u32,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickSessionReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 7; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOnlinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 8; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOfflinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 9; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOnlinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 10; }
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOfflinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 11; }
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 后端服务之间转发完整后端帧。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardToServerReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 12; }
    #[prost(uint32, tag = "1")]
    pub target_service_id: u32,
    /// 小于 0 时由网关选择最低负载实例。
    #[prost(int32, tag = "2")]
    pub target_instance_id: i32,
    /// 完整后端帧数据。
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// 来源由网关根据连接注册信息覆盖。
    #[prost(uint32, tag = "4")]
    pub source_service_id: u32,
    #[prost(uint32, tag = "5")]
    pub source_instance_id: u32,
}
/// 后端定期上报自己的负载。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceLoadReportPush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 13; }
    /// 0 最空闲，100 视为满载。
    #[prost(uint32, tag = "1")]
    pub load_score: u32,
    /// 是否接收绑定
    #[prost(bool, tag = "2")]
    pub accepting_bindings: bool,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// 网关返回服务绑定结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 14; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    #[prost(uint32, tag = "3")]
    pub instance_id: u32,
    /// 0=OK,1=NO_AVAILABLE_SERVICE,2=TARGET_SERVICE_UNREACHABLE。
    #[prost(uint32, tag = "4")]
    pub code: u32,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
/// 网关定时发给后端服务的心跳请求。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerPingReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 15; }
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
/// 后端服务回复网关心跳，nonce 必须原样返回。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerPongResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 16; }
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
