// This file is @generated by prost-build.
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceStatus {
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
    #[prost(bool, tag = "3")]
    pub online: bool,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerStatusPush {
    #[prost(message, repeated, tag = "1")]
    pub services: ::prost::alloc::vec::Vec<ServiceStatus>,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GatewayErrorResp {
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
