// This file is @generated by prost-build.
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceEndpoint {
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 3; }
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
    #[prost(uint32, tag = "3")]
    pub load_score: u32,
    #[prost(bool, tag = "4")]
    pub accepting_bindings: bool,
    #[prost(string, tag = "5")]
    pub load_message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 4; }
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(message, repeated, tag = "2")]
    pub servers: ::prost::alloc::vec::Vec<ServiceEndpoint>,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 5; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    #[prost(int32, tag = "3")]
    pub target_instance_id: i32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 6; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    #[prost(uint32, tag = "3")]
    pub instance_id: u32,
    #[prost(uint32, tag = "4")]
    pub code: u32,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 7; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 8; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    #[prost(uint32, tag = "3")]
    pub code: u32,
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickSessionReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 9; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickSessionRsp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 10; }
    #[prost(uint32, tag = "1")]
    pub code: u32,
    #[prost(uint32, tag = "2")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOnlinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 11; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOfflinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 12; }
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOnlinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 13; }
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOfflinePush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 14; }
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardToServerReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 15; }
    #[prost(uint32, tag = "1")]
    pub target_service_id: u32,
    #[prost(int32, tag = "2")]
    pub target_instance_id: i32,
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "4")]
    pub source_service_id: u32,
    #[prost(uint32, tag = "5")]
    pub source_instance_id: u32,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceLoadReportPush {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 16; }
    #[prost(uint32, tag = "1")]
    pub load_score: u32,
    #[prost(bool, tag = "2")]
    pub accepting_bindings: bool,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerPingReq {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 17; }
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerPongResp {
    /// @build_automatically_generate_message_id@    enum MsgId { None = 0; Id = 18; }
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
