// This file is @generated by prost-build.
/// 一个已经注册到网关的服务实例。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceEndpoint {
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 id。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// 后端服务注册到网关。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegReq {
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 id。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
    /// 当前负载，0 最空闲，100 视为满载。
    #[prost(uint32, tag = "3")]
    pub load_score: u32,
    /// 是否接受新的绑定。
    #[prost(bool, tag = "4")]
    pub accepting_bindings: bool,
    /// 负载或健康状态说明。
    #[prost(string, tag = "5")]
    pub load_message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `ServerRegReq`.
pub mod server_reg_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 100,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关返回服务注册结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerRegResp {
    /// 注册结果，0 表示成功。
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 网关当前已知的其他服务实例。
    #[prost(message, repeated, tag = "2")]
    pub servers: ::prost::alloc::vec::Vec<ServiceEndpoint>,
}
/// Nested message and enum types in `ServerRegResp`.
pub mod server_reg_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 101,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 请求网关把客户端绑定到某类服务。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceReq {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 要绑定的服务类型。
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    /// 指定实例 id；负数表示由网关自动选择。
    #[prost(int32, tag = "3")]
    pub target_instance_id: i32,
}
/// Nested message and enum types in `BindServiceReq`.
pub mod bind_service_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 102,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关返回绑定结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BindServiceResp {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 服务类型。
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    /// 实际绑定的服务实例 id。
    #[prost(uint32, tag = "3")]
    pub instance_id: u32,
    /// 绑定结果，0 表示成功。
    #[prost(uint32, tag = "4")]
    pub code: u32,
    /// 结果说明。
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `BindServiceResp`.
pub mod bind_service_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 103,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 请求网关解除客户端和某类服务的绑定。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceReq {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 要解绑的服务类型。
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
}
/// Nested message and enum types in `UnbindServiceReq`.
pub mod unbind_service_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 104,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关返回解绑结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnbindServiceResp {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 服务类型。
    #[prost(uint32, tag = "2")]
    pub service_id: u32,
    /// 解绑结果，0 表示成功。
    #[prost(uint32, tag = "3")]
    pub code: u32,
    /// 结果说明。
    #[prost(string, tag = "4")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `UnbindServiceResp`.
pub mod unbind_service_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 105,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 请求网关踢掉一个客户端。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickSessionReq {
    /// 要关闭的客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// Nested message and enum types in `KickSessionReq`.
pub mod kick_session_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 106,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关返回踢下线结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KickSessionRsp {
    /// 处理结果，0 表示已接受。
    #[prost(uint32, tag = "1")]
    pub code: u32,
    /// 客户端 session id。
    #[prost(uint32, tag = "2")]
    pub session_id: u32,
}
/// Nested message and enum types in `KickSessionRsp`.
pub mod kick_session_rsp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 107,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关通知后端：客户端已经上线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOnlinePush {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// Nested message and enum types in `SessionOnlinePush`.
pub mod session_online_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 108,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关通知后端：客户端已经下线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionOfflinePush {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
}
/// Nested message and enum types in `SessionOfflinePush`.
pub mod session_offline_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 109,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关通知后端：某个服务实例上线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOnlinePush {
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 id。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// Nested message and enum types in `ServerOnlinePush`.
pub mod server_online_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 110,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关通知后端：某个服务实例下线。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerOfflinePush {
    /// 服务类型。
    #[prost(uint32, tag = "1")]
    pub service_id: u32,
    /// 服务实例 id。
    #[prost(uint32, tag = "2")]
    pub instance_id: u32,
}
/// Nested message and enum types in `ServerOfflinePush`.
pub mod server_offline_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 111,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 请求网关把一段内部帧转发给其他后端服务。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ForwardToServerReq {
    /// 目标服务类型。
    #[prost(uint32, tag = "1")]
    pub target_service_id: u32,
    /// 目标实例 id；负数表示由网关自动选择。
    #[prost(int32, tag = "2")]
    pub target_instance_id: i32,
    /// 要转发的内部帧。
    #[prost(bytes = "vec", tag = "3")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// 来源服务类型，由网关校准。
    #[prost(uint32, tag = "4")]
    pub source_service_id: u32,
    /// 来源服务实例 id，由网关校准。
    #[prost(uint32, tag = "5")]
    pub source_instance_id: u32,
}
/// Nested message and enum types in `ForwardToServerReq`.
pub mod forward_to_server_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 112,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 后端上报自己的负载。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServiceLoadReportPush {
    /// 当前负载，0 最空闲，100 视为满载。
    #[prost(uint32, tag = "1")]
    pub load_score: u32,
    /// 是否接受新的绑定。
    #[prost(bool, tag = "2")]
    pub accepting_bindings: bool,
    /// 负载或健康状态说明。
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `ServiceLoadReportPush`.
pub mod service_load_report_push {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 113,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 网关发给后端的心跳。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerPingReq {
    /// 心跳随机数。
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
/// Nested message and enum types in `ServerPingReq`.
pub mod server_ping_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 114,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// 后端回复网关的心跳。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerPongResp {
    /// 从 ServerPingReq 原样带回的随机数。
    #[prost(uint64, tag = "1")]
    pub nonce: u64,
}
/// Nested message and enum types in `ServerPongResp`.
pub mod server_pong_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 115,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
