use bytes::BufMut;
use prost::{DecodeError, Message};

#[derive(Clone)]
pub enum MessageType {
    None,
    GameCommonSuccessResp(super::game::CommonSuccessResp),
    GameCommonErrorResp(super::game::CommonErrorResp),
    GameLoginReq(super::game::LoginReq),
    GameLoginResp(super::game::LoginResp),
    GameRegisterReq(super::game::RegisterReq),
    GameRegisterResp(super::game::RegisterResp),
    GamePlayerInfo(super::game::PlayerInfo),
    GameCreateCharacterReq(super::game::CreateCharacterReq),
    GameCreateCharacterResp(super::game::CreateCharacterResp),
    GameFetchCharacterListReq(super::game::FetchCharacterListReq),
    GameFetchCharacterListResp(super::game::FetchCharacterListResp),
    GameSelectCharacterReq(super::game::SelectCharacterReq),
    GameSelectCharacterResp(super::game::SelectCharacterResp),
    GamePlayerState(super::game::PlayerState),
    GameBattleJoinReq(super::game::BattleJoinReq),
    GameBattleJoinResp(super::game::BattleJoinResp),
    GameBattleCreateReq(super::game::BattleCreateReq),
    GameBattleCreateResp(super::game::BattleCreateResp),
    GameBattleInputPush(super::game::BattleInputPush),
    GameBattleSnapshotPush(super::game::BattleSnapshotPush),
    GatewayServerStatusPush(super::gateway::ServerStatusPush),
    GatewayGatewayErrorResp(super::gateway::GatewayErrorResp),
    GatewayServerRegReq(super::gateway::ServerRegReq),
    GatewayServerRegResp(super::gateway::ServerRegResp),
    GatewayBindServiceReq(super::gateway::BindServiceReq),
    GatewayUnbindServiceReq(super::gateway::UnbindServiceReq),
    GatewayUnbindServiceResp(super::gateway::UnbindServiceResp),
    GatewayKickSessionReq(super::gateway::KickSessionReq),
    GatewaySessionOnlinePush(super::gateway::SessionOnlinePush),
    GatewaySessionOfflinePush(super::gateway::SessionOfflinePush),
    GatewayServerOnlinePush(super::gateway::ServerOnlinePush),
    GatewayServerOfflinePush(super::gateway::ServerOfflinePush),
    GatewayForwardToServerReq(super::gateway::ForwardToServerReq),
    GatewayServiceLoadReportPush(super::gateway::ServiceLoadReportPush),
    GatewayBindServiceResp(super::gateway::BindServiceResp),
    GatewayServerPingReq(super::gateway::ServerPingReq),
    GatewayServerPongResp(super::gateway::ServerPongResp),
}

impl MessageType {
    pub fn is_none(&self) -> bool {
        matches!(self, MessageType::None)
    }
}

pub fn get_message_id(message: &MessageType) -> Option<u32> {
    match message {
        MessageType::GameCommonSuccessResp(_) => Some(900u32),
        MessageType::GameCommonErrorResp(_) => Some(901u32),
        MessageType::GameLoginReq(_) => Some(1000u32),
        MessageType::GameLoginResp(_) => Some(1001u32),
        MessageType::GameRegisterReq(_) => Some(1002u32),
        MessageType::GameRegisterResp(_) => Some(1003u32),
        MessageType::GamePlayerInfo(_) => Some(1100u32),
        MessageType::GameCreateCharacterReq(_) => Some(1200u32),
        MessageType::GameCreateCharacterResp(_) => Some(1201u32),
        MessageType::GameFetchCharacterListReq(_) => Some(1202u32),
        MessageType::GameFetchCharacterListResp(_) => Some(1203u32),
        MessageType::GameSelectCharacterReq(_) => Some(1204u32),
        MessageType::GameSelectCharacterResp(_) => Some(1205u32),
        MessageType::GamePlayerState(_) => Some(20000u32),
        MessageType::GameBattleJoinReq(_) => Some(20010u32),
        MessageType::GameBattleJoinResp(_) => Some(20011u32),
        MessageType::GameBattleCreateReq(_) => Some(20014u32),
        MessageType::GameBattleCreateResp(_) => Some(20015u32),
        MessageType::GameBattleInputPush(_) => Some(20012u32),
        MessageType::GameBattleSnapshotPush(_) => Some(20013u32),
        MessageType::GatewayServerStatusPush(_) => Some(1u32),
        MessageType::GatewayGatewayErrorResp(_) => Some(2u32),
        MessageType::GatewayServerRegReq(_) => Some(3u32),
        MessageType::GatewayServerRegResp(_) => Some(4u32),
        MessageType::GatewayBindServiceReq(_) => Some(5u32),
        MessageType::GatewayUnbindServiceReq(_) => Some(6u32),
        MessageType::GatewayUnbindServiceResp(_) => Some(17u32),
        MessageType::GatewayKickSessionReq(_) => Some(7u32),
        MessageType::GatewaySessionOnlinePush(_) => Some(8u32),
        MessageType::GatewaySessionOfflinePush(_) => Some(9u32),
        MessageType::GatewayServerOnlinePush(_) => Some(10u32),
        MessageType::GatewayServerOfflinePush(_) => Some(11u32),
        MessageType::GatewayForwardToServerReq(_) => Some(12u32),
        MessageType::GatewayServiceLoadReportPush(_) => Some(13u32),
        MessageType::GatewayBindServiceResp(_) => Some(14u32),
        MessageType::GatewayServerPingReq(_) => Some(15u32),
        MessageType::GatewayServerPongResp(_) => Some(16u32),
        _ => None,
    }
}

pub fn decode_message(message_id: u32, bytes: &[u8]) -> Result<MessageType, DecodeError> {
    match message_id {
        900u32 => match super::game::CommonSuccessResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameCommonSuccessResp(message)),
            Err(err) => Err(err),
        },
        901u32 => match super::game::CommonErrorResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameCommonErrorResp(message)),
            Err(err) => Err(err),
        },
        1000u32 => match super::game::LoginReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameLoginReq(message)),
            Err(err) => Err(err),
        },
        1001u32 => match super::game::LoginResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameLoginResp(message)),
            Err(err) => Err(err),
        },
        1002u32 => match super::game::RegisterReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameRegisterReq(message)),
            Err(err) => Err(err),
        },
        1003u32 => match super::game::RegisterResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameRegisterResp(message)),
            Err(err) => Err(err),
        },
        1100u32 => match super::game::PlayerInfo::decode(bytes) {
            Ok(message) => Ok(MessageType::GamePlayerInfo(message)),
            Err(err) => Err(err),
        },
        1200u32 => match super::game::CreateCharacterReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameCreateCharacterReq(message)),
            Err(err) => Err(err),
        },
        1201u32 => match super::game::CreateCharacterResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameCreateCharacterResp(message)),
            Err(err) => Err(err),
        },
        1202u32 => match super::game::FetchCharacterListReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameFetchCharacterListReq(message)),
            Err(err) => Err(err),
        },
        1203u32 => match super::game::FetchCharacterListResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameFetchCharacterListResp(message)),
            Err(err) => Err(err),
        },
        1204u32 => match super::game::SelectCharacterReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameSelectCharacterReq(message)),
            Err(err) => Err(err),
        },
        1205u32 => match super::game::SelectCharacterResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameSelectCharacterResp(message)),
            Err(err) => Err(err),
        },
        20000u32 => match super::game::PlayerState::decode(bytes) {
            Ok(message) => Ok(MessageType::GamePlayerState(message)),
            Err(err) => Err(err),
        },
        20010u32 => match super::game::BattleJoinReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameBattleJoinReq(message)),
            Err(err) => Err(err),
        },
        20011u32 => match super::game::BattleJoinResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameBattleJoinResp(message)),
            Err(err) => Err(err),
        },
        20014u32 => match super::game::BattleCreateReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GameBattleCreateReq(message)),
            Err(err) => Err(err),
        },
        20015u32 => match super::game::BattleCreateResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GameBattleCreateResp(message)),
            Err(err) => Err(err),
        },
        20012u32 => match super::game::BattleInputPush::decode(bytes) {
            Ok(message) => Ok(MessageType::GameBattleInputPush(message)),
            Err(err) => Err(err),
        },
        20013u32 => match super::game::BattleSnapshotPush::decode(bytes) {
            Ok(message) => Ok(MessageType::GameBattleSnapshotPush(message)),
            Err(err) => Err(err),
        },
        1u32 => match super::gateway::ServerStatusPush::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerStatusPush(message)),
            Err(err) => Err(err),
        },
        2u32 => match super::gateway::GatewayErrorResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayGatewayErrorResp(message)),
            Err(err) => Err(err),
        },
        3u32 => match super::gateway::ServerRegReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerRegReq(message)),
            Err(err) => Err(err),
        },
        4u32 => match super::gateway::ServerRegResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerRegResp(message)),
            Err(err) => Err(err),
        },
        5u32 => match super::gateway::BindServiceReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayBindServiceReq(message)),
            Err(err) => Err(err),
        },
        6u32 => match super::gateway::UnbindServiceReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayUnbindServiceReq(message)),
            Err(err) => Err(err),
        },
        17u32 => match super::gateway::UnbindServiceResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayUnbindServiceResp(message)),
            Err(err) => Err(err),
        },
        7u32 => match super::gateway::KickSessionReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayKickSessionReq(message)),
            Err(err) => Err(err),
        },
        8u32 => match super::gateway::SessionOnlinePush::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewaySessionOnlinePush(message)),
            Err(err) => Err(err),
        },
        9u32 => match super::gateway::SessionOfflinePush::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewaySessionOfflinePush(message)),
            Err(err) => Err(err),
        },
        10u32 => match super::gateway::ServerOnlinePush::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerOnlinePush(message)),
            Err(err) => Err(err),
        },
        11u32 => match super::gateway::ServerOfflinePush::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerOfflinePush(message)),
            Err(err) => Err(err),
        },
        12u32 => match super::gateway::ForwardToServerReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayForwardToServerReq(message)),
            Err(err) => Err(err),
        },
        13u32 => match super::gateway::ServiceLoadReportPush::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServiceLoadReportPush(message)),
            Err(err) => Err(err),
        },
        14u32 => match super::gateway::BindServiceResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayBindServiceResp(message)),
            Err(err) => Err(err),
        },
        15u32 => match super::gateway::ServerPingReq::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerPingReq(message)),
            Err(err) => Err(err),
        },
        16u32 => match super::gateway::ServerPongResp::decode(bytes) {
            Ok(message) => Ok(MessageType::GatewayServerPongResp(message)),
            Err(err) => Err(err),
        },
        _ => Err(DecodeError::new("unknown message id")),
    }
}

pub fn encode_message(message: &MessageType) -> Option<(u32, Vec<u8>)> {
    match message {
        MessageType::GameCommonSuccessResp(msg) => Some((900u32, msg.encode_to_vec())),
        MessageType::GameCommonErrorResp(msg) => Some((901u32, msg.encode_to_vec())),
        MessageType::GameLoginReq(msg) => Some((1000u32, msg.encode_to_vec())),
        MessageType::GameLoginResp(msg) => Some((1001u32, msg.encode_to_vec())),
        MessageType::GameRegisterReq(msg) => Some((1002u32, msg.encode_to_vec())),
        MessageType::GameRegisterResp(msg) => Some((1003u32, msg.encode_to_vec())),
        MessageType::GamePlayerInfo(msg) => Some((1100u32, msg.encode_to_vec())),
        MessageType::GameCreateCharacterReq(msg) => Some((1200u32, msg.encode_to_vec())),
        MessageType::GameCreateCharacterResp(msg) => Some((1201u32, msg.encode_to_vec())),
        MessageType::GameFetchCharacterListReq(msg) => Some((1202u32, msg.encode_to_vec())),
        MessageType::GameFetchCharacterListResp(msg) => Some((1203u32, msg.encode_to_vec())),
        MessageType::GameSelectCharacterReq(msg) => Some((1204u32, msg.encode_to_vec())),
        MessageType::GameSelectCharacterResp(msg) => Some((1205u32, msg.encode_to_vec())),
        MessageType::GamePlayerState(msg) => Some((20000u32, msg.encode_to_vec())),
        MessageType::GameBattleJoinReq(msg) => Some((20010u32, msg.encode_to_vec())),
        MessageType::GameBattleJoinResp(msg) => Some((20011u32, msg.encode_to_vec())),
        MessageType::GameBattleCreateReq(msg) => Some((20014u32, msg.encode_to_vec())),
        MessageType::GameBattleCreateResp(msg) => Some((20015u32, msg.encode_to_vec())),
        MessageType::GameBattleInputPush(msg) => Some((20012u32, msg.encode_to_vec())),
        MessageType::GameBattleSnapshotPush(msg) => Some((20013u32, msg.encode_to_vec())),
        MessageType::GatewayServerStatusPush(msg) => Some((1u32, msg.encode_to_vec())),
        MessageType::GatewayGatewayErrorResp(msg) => Some((2u32, msg.encode_to_vec())),
        MessageType::GatewayServerRegReq(msg) => Some((3u32, msg.encode_to_vec())),
        MessageType::GatewayServerRegResp(msg) => Some((4u32, msg.encode_to_vec())),
        MessageType::GatewayBindServiceReq(msg) => Some((5u32, msg.encode_to_vec())),
        MessageType::GatewayUnbindServiceReq(msg) => Some((6u32, msg.encode_to_vec())),
        MessageType::GatewayUnbindServiceResp(msg) => Some((17u32, msg.encode_to_vec())),
        MessageType::GatewayKickSessionReq(msg) => Some((7u32, msg.encode_to_vec())),
        MessageType::GatewaySessionOnlinePush(msg) => Some((8u32, msg.encode_to_vec())),
        MessageType::GatewaySessionOfflinePush(msg) => Some((9u32, msg.encode_to_vec())),
        MessageType::GatewayServerOnlinePush(msg) => Some((10u32, msg.encode_to_vec())),
        MessageType::GatewayServerOfflinePush(msg) => Some((11u32, msg.encode_to_vec())),
        MessageType::GatewayForwardToServerReq(msg) => Some((12u32, msg.encode_to_vec())),
        MessageType::GatewayServiceLoadReportPush(msg) => Some((13u32, msg.encode_to_vec())),
        MessageType::GatewayBindServiceResp(msg) => Some((14u32, msg.encode_to_vec())),
        MessageType::GatewayServerPingReq(msg) => Some((15u32, msg.encode_to_vec())),
        MessageType::GatewayServerPongResp(msg) => Some((16u32, msg.encode_to_vec())),
        _ => None,
    }
}

pub fn get_message_size(message: &MessageType) -> usize {
    match message {
        MessageType::GameCommonSuccessResp(msg) => msg.encoded_len(),
        MessageType::GameCommonErrorResp(msg) => msg.encoded_len(),
        MessageType::GameLoginReq(msg) => msg.encoded_len(),
        MessageType::GameLoginResp(msg) => msg.encoded_len(),
        MessageType::GameRegisterReq(msg) => msg.encoded_len(),
        MessageType::GameRegisterResp(msg) => msg.encoded_len(),
        MessageType::GamePlayerInfo(msg) => msg.encoded_len(),
        MessageType::GameCreateCharacterReq(msg) => msg.encoded_len(),
        MessageType::GameCreateCharacterResp(msg) => msg.encoded_len(),
        MessageType::GameFetchCharacterListReq(msg) => msg.encoded_len(),
        MessageType::GameFetchCharacterListResp(msg) => msg.encoded_len(),
        MessageType::GameSelectCharacterReq(msg) => msg.encoded_len(),
        MessageType::GameSelectCharacterResp(msg) => msg.encoded_len(),
        MessageType::GamePlayerState(msg) => msg.encoded_len(),
        MessageType::GameBattleJoinReq(msg) => msg.encoded_len(),
        MessageType::GameBattleJoinResp(msg) => msg.encoded_len(),
        MessageType::GameBattleCreateReq(msg) => msg.encoded_len(),
        MessageType::GameBattleCreateResp(msg) => msg.encoded_len(),
        MessageType::GameBattleInputPush(msg) => msg.encoded_len(),
        MessageType::GameBattleSnapshotPush(msg) => msg.encoded_len(),
        MessageType::GatewayServerStatusPush(msg) => msg.encoded_len(),
        MessageType::GatewayGatewayErrorResp(msg) => msg.encoded_len(),
        MessageType::GatewayServerRegReq(msg) => msg.encoded_len(),
        MessageType::GatewayServerRegResp(msg) => msg.encoded_len(),
        MessageType::GatewayBindServiceReq(msg) => msg.encoded_len(),
        MessageType::GatewayUnbindServiceReq(msg) => msg.encoded_len(),
        MessageType::GatewayUnbindServiceResp(msg) => msg.encoded_len(),
        MessageType::GatewayKickSessionReq(msg) => msg.encoded_len(),
        MessageType::GatewaySessionOnlinePush(msg) => msg.encoded_len(),
        MessageType::GatewaySessionOfflinePush(msg) => msg.encoded_len(),
        MessageType::GatewayServerOnlinePush(msg) => msg.encoded_len(),
        MessageType::GatewayServerOfflinePush(msg) => msg.encoded_len(),
        MessageType::GatewayForwardToServerReq(msg) => msg.encoded_len(),
        MessageType::GatewayServiceLoadReportPush(msg) => msg.encoded_len(),
        MessageType::GatewayBindServiceResp(msg) => msg.encoded_len(),
        MessageType::GatewayServerPingReq(msg) => msg.encoded_len(),
        MessageType::GatewayServerPongResp(msg) => msg.encoded_len(),
        _ => 0,
    }
}

pub fn encode_raw_message(message: &MessageType, buf: &mut impl BufMut) {
    match message {
        MessageType::GameCommonSuccessResp(msg) => msg.encode_raw(buf),
        MessageType::GameCommonErrorResp(msg) => msg.encode_raw(buf),
        MessageType::GameLoginReq(msg) => msg.encode_raw(buf),
        MessageType::GameLoginResp(msg) => msg.encode_raw(buf),
        MessageType::GameRegisterReq(msg) => msg.encode_raw(buf),
        MessageType::GameRegisterResp(msg) => msg.encode_raw(buf),
        MessageType::GamePlayerInfo(msg) => msg.encode_raw(buf),
        MessageType::GameCreateCharacterReq(msg) => msg.encode_raw(buf),
        MessageType::GameCreateCharacterResp(msg) => msg.encode_raw(buf),
        MessageType::GameFetchCharacterListReq(msg) => msg.encode_raw(buf),
        MessageType::GameFetchCharacterListResp(msg) => msg.encode_raw(buf),
        MessageType::GameSelectCharacterReq(msg) => msg.encode_raw(buf),
        MessageType::GameSelectCharacterResp(msg) => msg.encode_raw(buf),
        MessageType::GamePlayerState(msg) => msg.encode_raw(buf),
        MessageType::GameBattleJoinReq(msg) => msg.encode_raw(buf),
        MessageType::GameBattleJoinResp(msg) => msg.encode_raw(buf),
        MessageType::GameBattleCreateReq(msg) => msg.encode_raw(buf),
        MessageType::GameBattleCreateResp(msg) => msg.encode_raw(buf),
        MessageType::GameBattleInputPush(msg) => msg.encode_raw(buf),
        MessageType::GameBattleSnapshotPush(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerStatusPush(msg) => msg.encode_raw(buf),
        MessageType::GatewayGatewayErrorResp(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerRegReq(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerRegResp(msg) => msg.encode_raw(buf),
        MessageType::GatewayBindServiceReq(msg) => msg.encode_raw(buf),
        MessageType::GatewayUnbindServiceReq(msg) => msg.encode_raw(buf),
        MessageType::GatewayUnbindServiceResp(msg) => msg.encode_raw(buf),
        MessageType::GatewayKickSessionReq(msg) => msg.encode_raw(buf),
        MessageType::GatewaySessionOnlinePush(msg) => msg.encode_raw(buf),
        MessageType::GatewaySessionOfflinePush(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerOnlinePush(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerOfflinePush(msg) => msg.encode_raw(buf),
        MessageType::GatewayForwardToServerReq(msg) => msg.encode_raw(buf),
        MessageType::GatewayServiceLoadReportPush(msg) => msg.encode_raw(buf),
        MessageType::GatewayBindServiceResp(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerPingReq(msg) => msg.encode_raw(buf),
        MessageType::GatewayServerPongResp(msg) => msg.encode_raw(buf),
        _ => {}
    }
}

#[cfg(feature = "serde-serialize")]
pub fn serialize_to_json(message: &MessageType) -> serde_json::Result<String> {
    match message {
        MessageType::GameCommonSuccessResp(msg) => serde_json::to_string(&msg),
        MessageType::GameCommonErrorResp(msg) => serde_json::to_string(&msg),
        MessageType::GameLoginReq(msg) => serde_json::to_string(&msg),
        MessageType::GameLoginResp(msg) => serde_json::to_string(&msg),
        MessageType::GameRegisterReq(msg) => serde_json::to_string(&msg),
        MessageType::GameRegisterResp(msg) => serde_json::to_string(&msg),
        MessageType::GamePlayerInfo(msg) => serde_json::to_string(&msg),
        MessageType::GameCreateCharacterReq(msg) => serde_json::to_string(&msg),
        MessageType::GameCreateCharacterResp(msg) => serde_json::to_string(&msg),
        MessageType::GameFetchCharacterListReq(msg) => serde_json::to_string(&msg),
        MessageType::GameFetchCharacterListResp(msg) => serde_json::to_string(&msg),
        MessageType::GameSelectCharacterReq(msg) => serde_json::to_string(&msg),
        MessageType::GameSelectCharacterResp(msg) => serde_json::to_string(&msg),
        MessageType::GamePlayerState(msg) => serde_json::to_string(&msg),
        MessageType::GameBattleJoinReq(msg) => serde_json::to_string(&msg),
        MessageType::GameBattleJoinResp(msg) => serde_json::to_string(&msg),
        MessageType::GameBattleCreateReq(msg) => serde_json::to_string(&msg),
        MessageType::GameBattleCreateResp(msg) => serde_json::to_string(&msg),
        MessageType::GameBattleInputPush(msg) => serde_json::to_string(&msg),
        MessageType::GameBattleSnapshotPush(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerStatusPush(msg) => serde_json::to_string(&msg),
        MessageType::GatewayGatewayErrorResp(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerRegReq(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerRegResp(msg) => serde_json::to_string(&msg),
        MessageType::GatewayBindServiceReq(msg) => serde_json::to_string(&msg),
        MessageType::GatewayUnbindServiceReq(msg) => serde_json::to_string(&msg),
        MessageType::GatewayUnbindServiceResp(msg) => serde_json::to_string(&msg),
        MessageType::GatewayKickSessionReq(msg) => serde_json::to_string(&msg),
        MessageType::GatewaySessionOnlinePush(msg) => serde_json::to_string(&msg),
        MessageType::GatewaySessionOfflinePush(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerOnlinePush(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerOfflinePush(msg) => serde_json::to_string(&msg),
        MessageType::GatewayForwardToServerReq(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServiceLoadReportPush(msg) => serde_json::to_string(&msg),
        MessageType::GatewayBindServiceResp(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerPingReq(msg) => serde_json::to_string(&msg),
        MessageType::GatewayServerPongResp(msg) => serde_json::to_string(&msg),
        _ => Ok("null".into()),
    }
}
