// This file is @generated by prost-build.
/// game 服请求 town 服执行进入场景。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TownEnterSceneReq {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 登录态确认后的玩家 id。
    #[prost(int64, tag = "2")]
    pub player_id: i64,
    /// 要进入的目标类型。
    #[prost(enumeration = "super::types::SceneEnterType", tag = "3")]
    pub r#type: i32,
    /// 普通地图 id，type 为 Map 时有效。
    #[prost(uint32, tag = "4")]
    pub map_id: u32,
    /// 家园拥有者玩家 id，type 为 Home 时有效。
    #[prost(uint64, tag = "5")]
    pub owner_uid: u64,
    /// 玩家进入场景时的初始状态，player_id 由服务器覆盖。
    #[prost(message, optional, tag = "6")]
    pub state: ::core::option::Option<super::types::PlayerState>,
}
/// Nested message and enum types in `TownEnterSceneReq`.
pub mod town_enter_scene_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 61000,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// town 服返回给 game 服的进入场景结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TownEnterSceneResp {
    /// 结果码，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 承载该场景的 town 实例 id，用于 gateway 绑定。
    #[prost(uint32, tag = "3")]
    pub town_instance_id: u32,
    /// 当前场景公开信息，不包含 SceneId。
    #[prost(message, optional, tag = "4")]
    pub scene: ::core::option::Option<super::types::SceneInfo>,
    /// 当前场景内的玩家状态快照，包含自己。
    #[prost(message, repeated, tag = "5")]
    pub players: ::prost::alloc::vec::Vec<super::types::PlayerState>,
}
/// Nested message and enum types in `TownEnterSceneResp`.
pub mod town_enter_scene_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 61001,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// game 服请求 town 服执行离开场景。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TownLeaveSceneReq {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 登录态确认后的玩家 id。
    #[prost(int64, tag = "2")]
    pub player_id: i64,
}
/// Nested message and enum types in `TownLeaveSceneReq`.
pub mod town_leave_scene_req {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 61002,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
/// town 服返回给 game 服的离开场景结果。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TownLeaveSceneResp {
    /// 结果码，0 表示成功。
    #[prost(int32, tag = "1")]
    pub code: i32,
    /// 结果说明。
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Nested message and enum types in `TownLeaveSceneResp`.
pub mod town_leave_scene_resp {
    #[cfg_attr(
        feature = "serde-serialize",
        derive(serde::Serialize, serde::Deserialize)
    )]
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum MsgId {
        None = 0,
        Id = 61003,
    }
    impl MsgId {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                MsgId::None => "None",
                MsgId::Id => "Id",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "None" => Some(Self::None),
                "Id" => Some(Self::Id),
                _ => None,
            }
        }
    }
}
