// This file is @generated by prost-build.
/// 登录后下发的服务器配置。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerConfig {
    /// 最大角色数量。
    #[prost(int32, tag = "1")]
    pub max_character_count: i32,
}
/// 登录账号信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AccountInfo {
    /// 玩家 id。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// 账号名。
    #[prost(string, tag = "2")]
    pub account: ::prost::alloc::string::String,
    /// 昵称。
    #[prost(string, tag = "3")]
    pub nickname: ::prost::alloc::string::String,
}
/// 装备附魔属性。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EnchantProp {
    /// 属性配置 id。
    #[prost(int32, tag = "1")]
    pub attr_id: i32,
    /// 属性值。
    #[prost(int32, tag = "2")]
    pub value: i32,
}
/// 装备信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EquipmentInfo {
    /// 装备实例 id。
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 装备配置 id。
    #[prost(int64, tag = "2")]
    pub config_id: i64,
    /// 强化等级。
    #[prost(int32, tag = "3")]
    pub enhance_level: i32,
    /// 精炼等级。
    #[prost(int32, tag = "4")]
    pub refine_level: i32,
    /// 附魔属性列表。
    #[prost(message, repeated, tag = "5")]
    pub enchant_props: ::prost::alloc::vec::Vec<EnchantProp>,
    /// 装备槽位。
    #[prost(int32, tag = "6")]
    pub slot: i32,
}
/// 普通道具信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemInfo {
    /// 道具实例 id。
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 道具配置 id。
    #[prost(int64, tag = "2")]
    pub config_id: i64,
    /// 数量。
    #[prost(int32, tag = "3")]
    pub count: i32,
}
/// 创角默认外观槽（res_fashion id）。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DefaultSkin {
    /// 时装部位（FashionPosition：2 衣 / 4 发 / 7 皮肤）。
    #[prost(int32, tag = "1")]
    pub position: i32,
    /// res_fashion 配置 id。
    #[prost(int32, tag = "2")]
    pub res_fashion_id: i32,
}
/// 时装实例。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FashionInfo {
    /// 时装实例 id。
    #[prost(int64, tag = "1")]
    pub id: i64,
    /// 时装配置 id。
    #[prost(int32, tag = "2")]
    pub config_id: i32,
    /// 时装部位。
    #[prost(int32, tag = "3")]
    pub position: i32,
    /// 是否穿在身上。
    #[prost(bool, tag = "4")]
    pub worn: bool,
}
/// 背包信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InventoryInfo {
    /// 普通道具列表。
    #[prost(message, repeated, tag = "1")]
    pub items: ::prost::alloc::vec::Vec<ItemInfo>,
    /// 装备列表。
    #[prost(message, repeated, tag = "2")]
    pub equipments: ::prost::alloc::vec::Vec<EquipmentInfo>,
    /// 装扮列表。
    #[prost(message, repeated, tag = "3")]
    pub fashions: ::prost::alloc::vec::Vec<FashionInfo>,
}
/// 角色信息。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharacterInfo {
    /// 角色 id。
    #[prost(int64, tag = "1")]
    pub character_id: i64,
    /// 角色名。
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 职业 id。
    #[prost(int32, tag = "3")]
    pub class_id: i32,
    /// 性别。
    #[prost(int32, tag = "4")]
    pub gender: i32,
    /// 等级。
    #[prost(int32, tag = "5")]
    pub level: i32,
    /// 经验。
    #[prost(int64, tag = "6")]
    pub exp: i64,
    /// 金币。
    #[prost(int64, tag = "7")]
    pub gold: i64,
    /// 创角默认外观（发/衣/皮肤）。
    #[prost(message, repeated, tag = "8")]
    pub default_skins: ::prost::alloc::vec::Vec<DefaultSkin>,
    /// 拥有的全部装扮。
    #[prost(message, repeated, tag = "9")]
    pub fashions: ::prost::alloc::vec::Vec<FashionInfo>,
    /// 拥有+穿上的全部装备。
    #[prost(message, repeated, tag = "10")]
    pub equipments: ::prost::alloc::vec::Vec<EquipmentInfo>,
}
/// 城镇场景内玩家状态。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PlayerState {
    /// 玩家 id。客户端上报时服务端会使用登录态覆盖该字段。
    #[prost(int64, tag = "1")]
    pub player_id: i64,
    /// x 坐标。
    #[prost(float, tag = "2")]
    pub pos_x: f32,
    /// y 坐标。
    #[prost(float, tag = "3")]
    pub pos_y: f32,
    /// 当前血量。
    #[prost(int32, tag = "4")]
    pub hp: i32,
    /// 当前状态（当前播放的 motion 名，如 idle/walk）。
    #[prost(string, tag = "5")]
    pub state: ::prost::alloc::string::String,
    /// 职业 id，决定远端用哪个角色配置创建 avatar。
    #[prost(int32, tag = "6")]
    pub class_id: i32,
    /// 角色名。
    #[prost(string, tag = "7")]
    pub name: ::prost::alloc::string::String,
    /// z 坐标（高度）。
    #[prost(float, tag = "8")]
    pub pos_z: f32,
    /// 朝向，对应客户端 FacingDirection（0=左，1=右）。
    #[prost(int32, tag = "9")]
    pub facing: i32,
    /// 是否仍在主动移动（有移动意图/速度）。远端据此保持 walk，避免到点误切 idle。
    #[prost(bool, tag = "10")]
    pub moving: bool,
    /// 当前水平速度（像素/秒），用于远端斜向外推。
    #[prost(float, tag = "11")]
    pub vel_x: f32,
    #[prost(float, tag = "12")]
    pub vel_y: f32,
}
/// 下发给客户端的场景公开信息，不包含服务器内部 SceneId。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneInfo {
    /// 场景目标类型。
    #[prost(enumeration = "SceneEnterType", tag = "1")]
    pub r#type: i32,
    /// 普通地图 id，type 为 Map 时有效。
    #[prost(uint32, tag = "2")]
    pub map_id: u32,
    /// 家园拥有者玩家 id，type 为 Home 时有效。
    #[prost(uint64, tag = "3")]
    pub owner_uid: u64,
}
/// 创建战斗时传给 battle 服的玩家描述。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BattlePlayerSpec {
    /// 客户端 session id。
    #[prost(uint32, tag = "1")]
    pub session_id: u32,
    /// 玩家 id。
    #[prost(int64, tag = "2")]
    pub player_id: i64,
    /// 职业 id（对应客户端 JobType / class_id）。
    #[prost(int32, tag = "3")]
    pub class_id: i32,
    /// 角色显示名。
    #[prost(string, tag = "4")]
    pub name: ::prost::alloc::string::String,
    /// 角色 id（便于排查，可选）。
    #[prost(int64, tag = "5")]
    pub character_id: i64,
}
/// 城镇场景进入目标类型。
#[cfg_attr(feature = "serde-serialize", derive(serde::Serialize, serde::Deserialize))]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SceneEnterType {
    /// 无效类型。
    None = 0,
    /// 普通地图。
    Map = 1,
    /// 玩家家园。
    Home = 2,
}
impl SceneEnterType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            SceneEnterType::None => "None",
            SceneEnterType::Map => "Map",
            SceneEnterType::Home => "Home",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "None" => Some(Self::None),
            "Map" => Some(Self::Map),
            "Home" => Some(Self::Home),
            _ => None,
        }
    }
}
